// AUTO generated file from DDR Test logfile
#define params_mem_type DDR3
#define params_DDR_UMCTL2_ECC_MODE 0
#define params_DDR_UMCTL2_ECC_REGION_MAP 0
#define params_DDR_UMCTL2_ECC_REGION_MAP_GRANU 0
#define params_DDR_UMCTL2_ECC_REGION_MAP_OTHER 0
#define params_DDR_UMCTL2_DIS_AUTO_REFRESH 1
#define params_DDR_UMCTL2_SELFREF_EN 0
#define params_DDR_UMCTL2_POWERDOWN_EN 0
#define params_DDR_UMCTL2_PRE_CKE_X1024 147
#define params_DDR_UMCTL2_POST_CKE_X1024 1
#define params_DDR_UMCTL2_SKIP_DRAM_INIT 1
#define params_DDR_UMCTL2_DRAM_RSTN_X1024 59
#define params_DDR_UMCTL2_MR 2896
#define params_DDR_UMCTL2_EMR 4
#define params_DDR_UMCTL2_EMR2 16
#define params_DDR_UMCTL2_EMR3 0
#define params_DDR_UMCTL2_DEV_ZQINIT_X32 9
#define params_DDR_UMCTL2_DDR3 1
#define params_DDR_UMCTL2_EN_2T_TIMING_MODE 0
#define params_DDR_UMCTL2_DLL_OFF_MODE 0
#define params_DDR_UMCTL2_BURST_RDWR 4
#define params_DDR_UMCTL2_BURSTCHOP 0
#define params_DDR_UMCTL2_ACTIVE_RANKS 1
#define params_DDR_UMCTL2_WR2PRE 10
#define params_DDR_UMCTL2_T_FAW 13
#define params_DDR_UMCTL2_T_RAS_MAX 20
#define params_DDR_UMCTL2_T_RAS_MIN 11
#define params_DDR_UMCTL2_T_XP 2
#define params_DDR_UMCTL2_RD2PRE 2
#define params_DDR_UMCTL2_T_RC 15
#define params_DDR_UMCTL2_RD2WR 4
#define params_DDR_UMCTL2_WR2RD 8
#define params_DDR_UMCTL2_T_MOD 7
#define params_DDR_UMCTL2_T_MRD 2
#define params_DDR_UMCTL2_T_RCD 5
#define params_DDR_UMCTL2_T_CCD 2
#define params_DDR_UMCTL2_T_RRD 3
#define params_DDR_UMCTL2_T_RP 5
#define params_DDR_UMCTL2_T_CKSRX 4
#define params_DDR_UMCTL2_T_CKSRE 4
#define params_DDR_UMCTL2_T_CKESR 3
#define params_DDR_UMCTL2_T_CKE 2
#define params_DDR_UMCTL2_T_XS_X32 4
#define params_DDR_UMCTL2_T_XS_DLL_X32 8
#define params_DDR_UMCTL2_DFI_TPHY_WRLAT 2
#define params_DDR_UMCTL2_DFI_TPHY_WRDATA 1
#define params_DDR_UMCTL2_DFI_T_RDDATA_EN 3
#define params_DDR_UMCTL2_DFI_T_CTRL_DELAY 4
#define params_DDR_UMCTL2_DFI_T_DRAM_CLK_ENABLE 1
#define params_DDR_UMCTL2_DFI_T_DRAM_CLK_DISABLE 2
#define params_DDR_UMCTL2_DFI_T_WRDATA_DELAY 4
#define params_DDR_UMCTL2_DFI_INIT_COMPLETE_EN 0
#define params_DDR_UMCTL2_DIS_AUTO_CTRLUPD_SRX 1
#define params_DDR_UMCTL2_DIS_AUTO_CTRLUPD 1
#define params_DDR_UMCTL2_DFI_T_CTRLUPD_INTERVAL_MIN_X1024 64
#define params_DDR_UMCTL2_DFI_T_CTRLUPD_INTERVAL_MAX_X1024 255
#define params_DDR_UMCTL2_REFRESH_BURST 1
#define params_DDR_UMCTL2_T_RFC_NOM_X1_X32 74
#define params_DDR_UMCTL2_T_RFC_MIN 106
#define params_DDR_UMCTL2_RD_ODT_DELAY 0
#define params_DDR_UMCTL2_RD_ODT_HOLD 0
#define params_DDR_UMCTL2_WR_ODT_DELAY 0
#define params_DDR_UMCTL2_WR_ODT_HOLD 6
#define params_DDR_UMCTL2_BASE_ADDR 3
#define params_DDR_UMCTL2_NBLOCKS 4
#define params_DDR_UMCTL2_ADDRMAP_BANK_B2 25
#define params_DDR_UMCTL2_ADDRMAP_BANK_B1 25
#define params_DDR_UMCTL2_ADDRMAP_BANK_B0 25
#define params_DDR_UMCTL2_ADDRMAP_COL_B5 0
#define params_DDR_UMCTL2_ADDRMAP_COL_B4 0
#define params_DDR_UMCTL2_ADDRMAP_COL_B3 0
#define params_DDR_UMCTL2_ADDRMAP_COL_B2 0
#define params_DDR_UMCTL2_ADDRMAP_COL_B9 0
#define params_DDR_UMCTL2_ADDRMAP_COL_B8 0
#define params_DDR_UMCTL2_ADDRMAP_COL_B7 0
#define params_DDR_UMCTL2_ADDRMAP_COL_B6 0
#define params_DDR_UMCTL2_ADDRMAP_COL_B11 31
#define params_DDR_UMCTL2_ADDRMAP_COL_B10 0
#define params_DDR_UMCTL2_ADDRMAP_ROW_B0 5
#define params_DDR_UMCTL2_ADDRMAP_ROW_B1 5
#define params_DDR_UMCTL2_ADDRMAP_ROW_B2_10 5
#define params_DDR_UMCTL2_ADDRMAP_ROW_B11 5
#define params_DDR_UMCTL2_ADDRMAP_ROW_B12 5
#define params_DDR_UMCTL2_ADDRMAP_ROW_B13 5
#define params_DDR_UMCTL2_ADDRMAP_ROW_B14 5
#define params_DDR_UMCTL2_ADDRMAP_ROW_B15 5
#define params_DDR_UMCTL2_ADDRMAP_CS_BIT0 31
#define params_DDR_PHY_RRMODE 1
#define params_DDR_PHY_TREFPRD 4281
#define params_DDR_PHY_TPLLGS 800
#define params_DDR_PHY_TPLLPD 200
#define params_DDR_PHY_TPLLRST 600
#define params_DDR_PHY_TPLLLOCK 20000
#define params_DDR_PHY_PIR 115
#define params_DDR_PHY_DDR2T 0
#define params_DDR_PHY_DDRMD 3
#define params_DDR_PHY_MR0 2896
#define params_DDR_PHY_MR1 4
#define params_DDR_PHY_MR2 16
#define params_DDR_PHY_MR3 0
#define params_DDR_PHY_TRTP 5
#define params_DDR_PHY_TWTR 5
#define params_DDR_PHY_TRP 9
#define params_DDR_PHY_TRCD 9
#define params_DDR_PHY_TRAS 22
#define params_DDR_PHY_TRRD 5
#define params_DDR_PHY_TRC 30
#define params_DDR_PHY_TMRD 0
#define params_DDR_PHY_TMOD 1
#define params_DDR_PHY_TFAW 25
#define params_DDR_PHY_TRFC 211
#define params_DDR_PHY_TWLMRD 40
#define params_DDR_PHY_TWLO 5
#define params_DDR_PHY_TXS 512
#define params_DDR_PHY_TXP 15
#define params_DDR_PHY_TCKE 5
#define params_DDR_PHY_TDLLK 512
#define params_DDR_PHY_TDINIT0 30
#define params_DDR_PHY_TDINIT1 217
#define params_DDR_PHY_TDINIT2 12
#define params_DDR_PHY_TDINIT3 512
#define params_DDR_PHY_DQSRES 4
#define params_DDR_PHY_DQSNRES 12
#define params_DDR_PHY_CUAEN 1
#define params_DDR_PHY_SDRMODE 0
#define params_DDR_PHY_PIR 385
#define params_DDR_UMCTL2_SW_DONE 0
#define params_DDR_UMCTL2_DFI_INIT_COMPLETE_EN 1
#define params_DDR_UMCTL2_SW_DONE 1
#define params_DDR_UMCTL2_SW_DONE 0
#define params_DDR_UMCTL2_DFI_INIT_COMPLETE_EN 0
#define params_DDR_UMCTL2_SW_DONE 1
#define params_DDR_PHY_RANKEN 1
#define params_DDR_PHY_DTMPR 1
#define params_DDR_PHY_DTRPTN 7
#define params_DDR_PHY_PIR 3585
#define params_DDR_PHY_DTMPR 0
#define params_DDR_PHY_DTRANK 0
#define params_DDR_PHY_PIR 4097
#define params_DDR_PHY_PIR 57345
#define params_DDR_UMCTL2_DIS_AUTO_REFRESH 0
#define params_DDR_UMCTL2_POWERDOWN_EN 0
#define params_DDR_UMCTL2_SW_DONE 0
#define params_DDR_UMCTL2_DFI_INIT_COMPLETE_EN 1
#define params_DDR_UMCTL2_SW_DONE 1
#define params_DDR_UMCTL2_DIS_AUTO_REFRESH 0
#define params_DDR_UMCTL2_SELFREF_EN 0
#define params_DDR_UMCTL2_POWERDOWN_EN 0
#define params_DDR_UMCTL2_PCTRL_0_PORT_EN 1
#define params_DDR_UMCTL2_PCTRL_1_PORT_EN 1
#define params_DDR_UMCTL2_PCTRL_2_PORT_EN 1
