/* SPDX-License-Identifier: (GPL-2.0 OR MIT) */
/*
 * Microchip LAN966x registers
 *
 * License: Dual MIT/GPL
 * Copyright (c) 2020 Microchip Technology Inc.
 */

/* This file is autogenerated by cml-utils 2021-03-07 15:39:44 +0100.
 * Commit ID: 6ceb5e65f7db2b344911f2a8a23beee182711456 (dirty)
 */

#ifndef _LAN966X_REGS_H_
#define _LAN966X_REGS_H_

#define BUILD_ID_REG GCB_BUILDID
#define BUILD_ID 1606729209

#define TARGET_AES_OFFSET 0xe004c000
#define TARGET_AESB_ASC_OFFSET 0xe0050000
#define TARGET_AFI_OFFSET 0xe0120000
#define TARGET_ANA_OFFSET 0xe0140000
#define TARGET_CA7_DBG_OFFSET 0xe8800000
#define TARGET_CHIP_TOP_OFFSET 0xe0010000
#define TARGET_CPU_OFFSET 0xe00c0000
#define TARGET_CPU_SYSCNT_OFFSET 0xe8843000
#define TARGET_CPU_SYSCNT_RO_OFFSET 0xe8900000
#define TARGET_DDR_PHY_OFFSET 0xe0084000
#define TARGET_DDR_UMCTL2_OFFSET 0xe0080000
#define TARGET_DEV_0_OFFSET 0xe0034000
#define TARGET_DEV_1_OFFSET 0xe0038000
#define TARGET_DEV_2_OFFSET 0xe003c000
#define TARGET_DEV_3_OFFSET 0xe0040000
#define TARGET_DEV_4_OFFSET 0xe0044000
#define TARGET_DEV_5_OFFSET 0xe0048000
#define TARGET_DEV_6_OFFSET 0xe004c000
#define TARGET_DEV_7_OFFSET 0xe0050000
#define TARGET_FDMA_OFFSET 0xe00c0400
#define TARGET_FLEXCOM_0_OFFSET 0xe0040000
#define TARGET_FLEXCOM_1_OFFSET 0xe0044000
#define TARGET_FLEXCOM_2_OFFSET 0xe0060000
#define TARGET_FLEXCOM_3_OFFSET 0xe0064000
#define TARGET_FLEXCOM_4_OFFSET 0xe0070000
#define TARGET_GCB_OFFSET 0xe0004000
#define TARGET_GIC400_OFFSET 0xe8c10000
#define TARGET_GPV_OFFSET 0xe8b00000
#define TARGET_HICM_OFFSET 0xe0810000
#define TARGET_HMATRIX2_OFFSET 0xe0800000
#define TARGET_HSIO_OFFSET 0xe002c000
#define TARGET_MCAN_0_OFFSET 0xe081c000
#define TARGET_MCAN_1_OFFSET 0xe0820000
#define TARGET_MEP_OFFSET 0xe001c000
#define TARGET_ORG_0_OFFSET 0xe0000000
#define TARGET_ORG_1_OFFSET 0xe0400000
#define TARGET_OTP_OFFSET 0xe0021000
#define TARGET_PCIE_CFG_OFFSET 0xe00d0000
#define TARGET_PCIE_DBI_OFFSET 0xe0400000
#define TARGET_PTP_OFFSET 0xe000c000
#define TARGET_QS_OFFSET 0xe0008000
#define TARGET_QSPI_0_OFFSET 0xe0804000
#define TARGET_QSPI_1_OFFSET 0xe0054000
#define TARGET_QSPI_2_OFFSET 0xe0834000
#define TARGET_QSYS_OFFSET 0xe0100000
#define TARGET_REW_OFFSET 0xe0014000
#define TARGET_RTE_OFFSET 0xe0600000
#define TARGET_SDMMC_OFFSET 0xe0830000
#define TARGET_SHA_OFFSET 0xe006c000
#define TARGET_SJTAG_OFFSET 0xe0020000
#define TARGET_SUNRISE_TOP_OFFSET 0xe0030000
#define TARGET_SYS_OFFSET 0xe0028000
#define TARGET_TIMER1_OFFSET 0xe0824000
#define TARGET_TIMERS_OFFSET 0xe008c000
#define TARGET_TRNG_OFFSET 0xe0048000
#define TARGET_TZAESBNS_OFFSET 0xe0814000
#define TARGET_TZAESBS_OFFSET 0xe0818000
#define TARGET_TZPM_OFFSET 0xe0004000
#define TARGET_UDPHS0_OFFSET 0xe0808000
#define TARGET_UVOV_OFFSET 0xe0094000
#define TARGET_VCAP_0_OFFSET 0xe0018000
#define TARGET_VCAP_1_OFFSET 0xe0020000
#define TARGET_VCAP_2_OFFSET 0xe0024000
#define TARGET_WDT_OFFSET 0xe0090000
#define TARGET_XDMAC_OFFSET 0xe0068000


/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RBAR0 */
#define AESB_ASC_TZAESBASC_RBAR0  0x00

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RTAR0 */
#define AESB_ASC_TZAESBASC_RTAR0  0x04

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RBAR1 */
#define AESB_ASC_TZAESBASC_RBAR1  0x08

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RTAR1 */
#define AESB_ASC_TZAESBASC_RTAR1  0x0c

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RBAR2 */
#define AESB_ASC_TZAESBASC_RBAR2  0x10

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RTAR2 */
#define AESB_ASC_TZAESBASC_RTAR2  0x14

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RBAR3 */
#define AESB_ASC_TZAESBASC_RBAR3  0x18

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RTAR3 */
#define AESB_ASC_TZAESBASC_RTAR3  0x1c

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RBAR4 */
#define AESB_ASC_TZAESBASC_RBAR4  0x20

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RTAR4 */
#define AESB_ASC_TZAESBASC_RTAR4  0x24

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RBAR5 */
#define AESB_ASC_TZAESBASC_RBAR5  0x28

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RTAR5 */
#define AESB_ASC_TZAESBASC_RTAR5  0x2c

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RBAR6 */
#define AESB_ASC_TZAESBASC_RBAR6  0x30

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RTAR6 */
#define AESB_ASC_TZAESBASC_RTAR6  0x34

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RBAR7 */
#define AESB_ASC_TZAESBASC_RBAR7  0x38

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RTAR7 */
#define AESB_ASC_TZAESBASC_RTAR7  0x3c

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RSECR */
#define AESB_ASC_TZAESBASC_RSECR  0x80

#define AESB_ASC_TZAESBASC_RSECR_SECx(x)         ((x) & GENMASK(7, 0))
#define AESB_ASC_TZAESBASC_RSECR_SECx_M          GENMASK(7, 0)
#define AESB_ASC_TZAESBASC_RSECR_SECx_X(x)       ((x) & GENMASK(7, 0))

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RER */
#define AESB_ASC_TZAESBASC_RER    0x84

#define AESB_ASC_TZAESBASC_RER_ENx(x)            ((x) & GENMASK(7, 0))
#define AESB_ASC_TZAESBASC_RER_ENx_M             GENMASK(7, 0)
#define AESB_ASC_TZAESBASC_RER_ENx_X(x)          ((x) & GENMASK(7, 0))

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RDR */
#define AESB_ASC_TZAESBASC_RDR    0x88

#define AESB_ASC_TZAESBASC_RDR_DISx(x)           ((x) & GENMASK(7, 0))
#define AESB_ASC_TZAESBASC_RDR_DISx_M            GENMASK(7, 0)
#define AESB_ASC_TZAESBASC_RDR_DISx_X(x)         ((x) & GENMASK(7, 0))

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RSR */
#define AESB_ASC_TZAESBASC_RSR    0x8c

#define AESB_ASC_TZAESBASC_RSR_ESx(x)            ((x) & GENMASK(7, 0))
#define AESB_ASC_TZAESBASC_RSR_ESx_M             GENMASK(7, 0)
#define AESB_ASC_TZAESBASC_RSR_ESx_X(x)          ((x) & GENMASK(7, 0))

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RESR */
#define AESB_ASC_TZAESBASC_RESR   0x90

#define AESB_ASC_TZAESBASC_RESR_AERx(x)          ((x) & GENMASK(7, 0))
#define AESB_ASC_TZAESBASC_RESR_AERx_M           GENMASK(7, 0)
#define AESB_ASC_TZAESBASC_RESR_AERx_X(x)        ((x) & GENMASK(7, 0))

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_RSSR */
#define AESB_ASC_TZAESBASC_RSSR   0x94

#define AESB_ASC_TZAESBASC_RSSR_SYNC(x)          ((x) & GENMASK(0, 0))
#define AESB_ASC_TZAESBASC_RSSR_SYNC_M           GENMASK(0, 0)
#define AESB_ASC_TZAESBASC_RSSR_SYNC_X(x)        ((x) & GENMASK(0, 0))

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_WPMR */
#define AESB_ASC_TZAESBASC_WPMR   0xe4

#define AESB_ASC_TZAESBASC_WPMR_WPKEY(x)         (((x) << 8) & GENMASK(31, 8))
#define AESB_ASC_TZAESBASC_WPMR_WPKEY_M          GENMASK(31, 8)
#define AESB_ASC_TZAESBASC_WPMR_WPKEY_X(x)       (((x) & GENMASK(31, 8)) >> 8)

#define AESB_ASC_TZAESBASC_WPMR_WPEN(x)          ((x) & GENMASK(0, 0))
#define AESB_ASC_TZAESBASC_WPMR_WPEN_M           GENMASK(0, 0)
#define AESB_ASC_TZAESBASC_WPMR_WPEN_X(x)        ((x) & GENMASK(0, 0))

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_WPSR */
#define AESB_ASC_TZAESBASC_WPSR   0xe8

#define AESB_ASC_TZAESBASC_WPSR_WPSRC(x)         (((x) << 8) & GENMASK(23, 8))
#define AESB_ASC_TZAESBASC_WPSR_WPSRC_M          GENMASK(23, 8)
#define AESB_ASC_TZAESBASC_WPSR_WPSRC_X(x)       (((x) & GENMASK(23, 8)) >> 8)

#define AESB_ASC_TZAESBASC_WPSR_WPVS(x)          ((x) & GENMASK(0, 0))
#define AESB_ASC_TZAESBASC_WPSR_WPVS_M           GENMASK(0, 0)
#define AESB_ASC_TZAESBASC_WPSR_WPVS_X(x)        ((x) & GENMASK(0, 0))

/*      AESB_ASC:AESB_ASC_REGS:TZAESBASC_VERSION */
#define AESB_ASC_TZAESBASC_VERSION 0xfc

#define AESB_ASC_TZAESBASC_VERSION_MFN(x)        (((x) << 16) & GENMASK(18, 16))
#define AESB_ASC_TZAESBASC_VERSION_MFN_M         GENMASK(18, 16)
#define AESB_ASC_TZAESBASC_VERSION_MFN_X(x)      (((x) & GENMASK(18, 16)) >> 16)

#define AESB_ASC_TZAESBASC_VERSION_VERSION(x)    ((x) & GENMASK(11, 0))
#define AESB_ASC_TZAESBASC_VERSION_VERSION_M     GENMASK(11, 0)
#define AESB_ASC_TZAESBASC_VERSION_VERSION_X(x)  ((x) & GENMASK(11, 0))

/*      CPU_SYSCNT:CXTSGEN_REGISTERS:CNTCR */
#define CPU_SYSCNT_CNTCR          0x00

#define CPU_SYSCNT_CNTCR_CNTCR_EN(x)             ((x) & GENMASK(0, 0))
#define CPU_SYSCNT_CNTCR_CNTCR_EN_M              GENMASK(0, 0)
#define CPU_SYSCNT_CNTCR_CNTCR_EN_X(x)           ((x) & GENMASK(0, 0))

#define CPU_SYSCNT_CNTCR_CNTCR_HDBG(x)           (((x) << 1) & GENMASK(1, 1))
#define CPU_SYSCNT_CNTCR_CNTCR_HDBG_M            GENMASK(1, 1)
#define CPU_SYSCNT_CNTCR_CNTCR_HDBG_X(x)         (((x) & GENMASK(1, 1)) >> 1)

/*      CPU_SYSCNT:CXTSGEN_REGISTERS:CNTSR */
#define CPU_SYSCNT_CNTSR          0x04

#define CPU_SYSCNT_CNTSR_CNTSR_DBGH(x)           (((x) << 1) & GENMASK(1, 1))
#define CPU_SYSCNT_CNTSR_CNTSR_DBGH_M            GENMASK(1, 1)
#define CPU_SYSCNT_CNTSR_CNTSR_DBGH_X(x)         (((x) & GENMASK(1, 1)) >> 1)

/*      CPU_SYSCNT:CXTSGEN_REGISTERS:CNTCVL */
#define CPU_SYSCNT_CNTCVL         0x08

/*      CPU_SYSCNT:CXTSGEN_REGISTERS:CNTCVU */
#define CPU_SYSCNT_CNTCVU         0x0c

/*      CPU_SYSCNT:CXTSGEN_REGISTERS:CNTFID0 */
#define CPU_SYSCNT_CNTFID0        0x20

/*      CPU_SYSCNT:CXTSGEN_REGISTERS:PIDR0 */
#define CPU_SYSCNT_PIDR0          0xfe0

#define CPU_SYSCNT_PIDR0_PART_0(x)               ((x) & GENMASK(7, 0))
#define CPU_SYSCNT_PIDR0_PART_0_M                GENMASK(7, 0)
#define CPU_SYSCNT_PIDR0_PART_0_X(x)             ((x) & GENMASK(7, 0))

/*      CPU_SYSCNT:CXTSGEN_REGISTERS:PIDR1 */
#define CPU_SYSCNT_PIDR1          0xfe4

#define CPU_SYSCNT_PIDR1_PART_1(x)               ((x) & GENMASK(3, 0))
#define CPU_SYSCNT_PIDR1_PART_1_M                GENMASK(3, 0)
#define CPU_SYSCNT_PIDR1_PART_1_X(x)             ((x) & GENMASK(3, 0))

#define CPU_SYSCNT_PIDR1_DES_0(x)                (((x) << 4) & GENMASK(7, 4))
#define CPU_SYSCNT_PIDR1_DES_0_M                 GENMASK(7, 4)
#define CPU_SYSCNT_PIDR1_DES_0_X(x)              (((x) & GENMASK(7, 4)) >> 4)

/*      CPU_SYSCNT:CXTSGEN_REGISTERS:PIDR2 */
#define CPU_SYSCNT_PIDR2          0xfe8

#define CPU_SYSCNT_PIDR2_DES_1(x)                ((x) & GENMASK(2, 0))
#define CPU_SYSCNT_PIDR2_DES_1_M                 GENMASK(2, 0)
#define CPU_SYSCNT_PIDR2_DES_1_X(x)              ((x) & GENMASK(2, 0))

#define CPU_SYSCNT_PIDR2_JEDEC(x)                (((x) << 3) & GENMASK(3, 3))
#define CPU_SYSCNT_PIDR2_JEDEC_M                 GENMASK(3, 3)
#define CPU_SYSCNT_PIDR2_JEDEC_X(x)              (((x) & GENMASK(3, 3)) >> 3)

#define CPU_SYSCNT_PIDR2_REVISION(x)             (((x) << 4) & GENMASK(7, 4))
#define CPU_SYSCNT_PIDR2_REVISION_M              GENMASK(7, 4)
#define CPU_SYSCNT_PIDR2_REVISION_X(x)           (((x) & GENMASK(7, 4)) >> 4)

/*      CPU_SYSCNT:CXTSGEN_REGISTERS:PIDR3 */
#define CPU_SYSCNT_PIDR3          0xfec

#define CPU_SYSCNT_PIDR3_CMOD(x)                 ((x) & GENMASK(3, 0))
#define CPU_SYSCNT_PIDR3_CMOD_M                  GENMASK(3, 0)
#define CPU_SYSCNT_PIDR3_CMOD_X(x)               ((x) & GENMASK(3, 0))

#define CPU_SYSCNT_PIDR3_REVAND(x)               (((x) << 4) & GENMASK(7, 4))
#define CPU_SYSCNT_PIDR3_REVAND_M                GENMASK(7, 4)
#define CPU_SYSCNT_PIDR3_REVAND_X(x)             (((x) & GENMASK(7, 4)) >> 4)

/*      CPU_SYSCNT:CXTSGEN_REGISTERS:PIDR4 */
#define CPU_SYSCNT_PIDR4          0xfd0

#define CPU_SYSCNT_PIDR4_DES_2(x)                ((x) & GENMASK(3, 0))
#define CPU_SYSCNT_PIDR4_DES_2_M                 GENMASK(3, 0)
#define CPU_SYSCNT_PIDR4_DES_2_X(x)              ((x) & GENMASK(3, 0))

#define CPU_SYSCNT_PIDR4_SIZE(x)                 (((x) << 4) & GENMASK(7, 4))
#define CPU_SYSCNT_PIDR4_SIZE_M                  GENMASK(7, 4)
#define CPU_SYSCNT_PIDR4_SIZE_X(x)               (((x) & GENMASK(7, 4)) >> 4)

/*      CPU_SYSCNT:CXTSGEN_REGISTERS:CIDR0 */
#define CPU_SYSCNT_CIDR0          0xff0

#define CPU_SYSCNT_CIDR0_PRMBL_0(x)              ((x) & GENMASK(7, 0))
#define CPU_SYSCNT_CIDR0_PRMBL_0_M               GENMASK(7, 0)
#define CPU_SYSCNT_CIDR0_PRMBL_0_X(x)            ((x) & GENMASK(7, 0))

/*      CPU_SYSCNT:CXTSGEN_REGISTERS:CIDR1 */
#define CPU_SYSCNT_CIDR1          0xff4

#define CPU_SYSCNT_CIDR1_PRMBL_1(x)              ((x) & GENMASK(3, 0))
#define CPU_SYSCNT_CIDR1_PRMBL_1_M               GENMASK(3, 0)
#define CPU_SYSCNT_CIDR1_PRMBL_1_X(x)            ((x) & GENMASK(3, 0))

#define CPU_SYSCNT_CIDR1_CLASS(x)                (((x) << 4) & GENMASK(7, 4))
#define CPU_SYSCNT_CIDR1_CLASS_M                 GENMASK(7, 4)
#define CPU_SYSCNT_CIDR1_CLASS_X(x)              (((x) & GENMASK(7, 4)) >> 4)

/*      CPU_SYSCNT:CXTSGEN_REGISTERS:CIDR2 */
#define CPU_SYSCNT_CIDR2          0xff8

#define CPU_SYSCNT_CIDR2_PRMBL_2(x)              ((x) & GENMASK(7, 0))
#define CPU_SYSCNT_CIDR2_PRMBL_2_M               GENMASK(7, 0)
#define CPU_SYSCNT_CIDR2_PRMBL_2_X(x)            ((x) & GENMASK(7, 0))

/*      CPU_SYSCNT:CXTSGEN_REGISTERS:CIDR3 */
#define CPU_SYSCNT_CIDR3          0xffc

#define CPU_SYSCNT_CIDR3_PRMBL_3(x)              ((x) & GENMASK(7, 0))
#define CPU_SYSCNT_CIDR3_PRMBL_3_M               GENMASK(7, 0)
#define CPU_SYSCNT_CIDR3_PRMBL_3_X(x)            ((x) & GENMASK(7, 0))

/*      CPU_SYSCNT_RO:CXTSGEN_READ_REGISTERS:CNTCVL */
#define CPU_SYSCNT_RO_CNTCVL      0x00

/*      CPU_SYSCNT_RO:CXTSGEN_READ_REGISTERS:CNTCVU */
#define CPU_SYSCNT_RO_CNTCVU      0x04

/*      CPU_SYSCNT_RO:CXTSGEN_READ_REGISTERS:PIDR0 */
#define CPU_SYSCNT_RO_PIDR0       0xfe0

#define CPU_SYSCNT_RO_PIDR0_PART_0(x)            ((x) & GENMASK(7, 0))
#define CPU_SYSCNT_RO_PIDR0_PART_0_M             GENMASK(7, 0)
#define CPU_SYSCNT_RO_PIDR0_PART_0_X(x)          ((x) & GENMASK(7, 0))

/*      CPU_SYSCNT_RO:CXTSGEN_READ_REGISTERS:PIDR1 */
#define CPU_SYSCNT_RO_PIDR1       0xfe4

#define CPU_SYSCNT_RO_PIDR1_PART_1(x)            ((x) & GENMASK(3, 0))
#define CPU_SYSCNT_RO_PIDR1_PART_1_M             GENMASK(3, 0)
#define CPU_SYSCNT_RO_PIDR1_PART_1_X(x)          ((x) & GENMASK(3, 0))

#define CPU_SYSCNT_RO_PIDR1_DES_0(x)             (((x) << 4) & GENMASK(7, 4))
#define CPU_SYSCNT_RO_PIDR1_DES_0_M              GENMASK(7, 4)
#define CPU_SYSCNT_RO_PIDR1_DES_0_X(x)           (((x) & GENMASK(7, 4)) >> 4)

/*      CPU_SYSCNT_RO:CXTSGEN_READ_REGISTERS:PIDR2 */
#define CPU_SYSCNT_RO_PIDR2       0xfe8

#define CPU_SYSCNT_RO_PIDR2_DES_1(x)             ((x) & GENMASK(2, 0))
#define CPU_SYSCNT_RO_PIDR2_DES_1_M              GENMASK(2, 0)
#define CPU_SYSCNT_RO_PIDR2_DES_1_X(x)           ((x) & GENMASK(2, 0))

#define CPU_SYSCNT_RO_PIDR2_JEDEC(x)             (((x) << 3) & GENMASK(3, 3))
#define CPU_SYSCNT_RO_PIDR2_JEDEC_M              GENMASK(3, 3)
#define CPU_SYSCNT_RO_PIDR2_JEDEC_X(x)           (((x) & GENMASK(3, 3)) >> 3)

#define CPU_SYSCNT_RO_PIDR2_REVISION(x)          (((x) << 4) & GENMASK(7, 4))
#define CPU_SYSCNT_RO_PIDR2_REVISION_M           GENMASK(7, 4)
#define CPU_SYSCNT_RO_PIDR2_REVISION_X(x)        (((x) & GENMASK(7, 4)) >> 4)

/*      CPU_SYSCNT_RO:CXTSGEN_READ_REGISTERS:PIDR3 */
#define CPU_SYSCNT_RO_PIDR3       0xfec

#define CPU_SYSCNT_RO_PIDR3_CMOD(x)              ((x) & GENMASK(3, 0))
#define CPU_SYSCNT_RO_PIDR3_CMOD_M               GENMASK(3, 0)
#define CPU_SYSCNT_RO_PIDR3_CMOD_X(x)            ((x) & GENMASK(3, 0))

#define CPU_SYSCNT_RO_PIDR3_REVAND(x)            (((x) << 4) & GENMASK(7, 4))
#define CPU_SYSCNT_RO_PIDR3_REVAND_M             GENMASK(7, 4)
#define CPU_SYSCNT_RO_PIDR3_REVAND_X(x)          (((x) & GENMASK(7, 4)) >> 4)

/*      CPU_SYSCNT_RO:CXTSGEN_READ_REGISTERS:PIDR4 */
#define CPU_SYSCNT_RO_PIDR4       0xfd0

#define CPU_SYSCNT_RO_PIDR4_DES_2(x)             ((x) & GENMASK(3, 0))
#define CPU_SYSCNT_RO_PIDR4_DES_2_M              GENMASK(3, 0)
#define CPU_SYSCNT_RO_PIDR4_DES_2_X(x)           ((x) & GENMASK(3, 0))

#define CPU_SYSCNT_RO_PIDR4_SIZE(x)              (((x) << 4) & GENMASK(7, 4))
#define CPU_SYSCNT_RO_PIDR4_SIZE_M               GENMASK(7, 4)
#define CPU_SYSCNT_RO_PIDR4_SIZE_X(x)            (((x) & GENMASK(7, 4)) >> 4)

/*      CPU_SYSCNT_RO:CXTSGEN_READ_REGISTERS:CIDR0 */
#define CPU_SYSCNT_RO_CIDR0       0xff0

#define CPU_SYSCNT_RO_CIDR0_PRMBL_0(x)           ((x) & GENMASK(7, 0))
#define CPU_SYSCNT_RO_CIDR0_PRMBL_0_M            GENMASK(7, 0)
#define CPU_SYSCNT_RO_CIDR0_PRMBL_0_X(x)         ((x) & GENMASK(7, 0))

/*      CPU_SYSCNT_RO:CXTSGEN_READ_REGISTERS:CIDR1 */
#define CPU_SYSCNT_RO_CIDR1       0xff4

#define CPU_SYSCNT_RO_CIDR1_PRMBL_1(x)           ((x) & GENMASK(3, 0))
#define CPU_SYSCNT_RO_CIDR1_PRMBL_1_M            GENMASK(3, 0)
#define CPU_SYSCNT_RO_CIDR1_PRMBL_1_X(x)         ((x) & GENMASK(3, 0))

#define CPU_SYSCNT_RO_CIDR1_CLASS(x)             (((x) << 4) & GENMASK(7, 4))
#define CPU_SYSCNT_RO_CIDR1_CLASS_M              GENMASK(7, 4)
#define CPU_SYSCNT_RO_CIDR1_CLASS_X(x)           (((x) & GENMASK(7, 4)) >> 4)

/*      CPU_SYSCNT_RO:CXTSGEN_READ_REGISTERS:CIDR2 */
#define CPU_SYSCNT_RO_CIDR2       0xff8

#define CPU_SYSCNT_RO_CIDR2_PRMBL_2(x)           ((x) & GENMASK(7, 0))
#define CPU_SYSCNT_RO_CIDR2_PRMBL_2_M            GENMASK(7, 0)
#define CPU_SYSCNT_RO_CIDR2_PRMBL_2_X(x)         ((x) & GENMASK(7, 0))

/*      CPU_SYSCNT_RO:CXTSGEN_READ_REGISTERS:CIDR3 */
#define CPU_SYSCNT_RO_CIDR3       0xffc

#define CPU_SYSCNT_RO_CIDR3_PRMBL_3(x)           ((x) & GENMASK(7, 0))
#define CPU_SYSCNT_RO_CIDR3_PRMBL_3_M            GENMASK(7, 0)
#define CPU_SYSCNT_RO_CIDR3_PRMBL_3_X(x)         ((x) & GENMASK(7, 0))

/*      HMATRIX2:HMATRIX2_REGS:MATRIX_SRTSR0 */
#define HMATRIX2_MATRIX_SRTSR0    0x280

#define HMATRIX2_MATRIX_SRTSR0_SRTOP7_SRTSR0(x)  (((x) << 28) & GENMASK(31, 28))
#define HMATRIX2_MATRIX_SRTSR0_SRTOP7_SRTSR0_M   GENMASK(31, 28)
#define HMATRIX2_MATRIX_SRTSR0_SRTOP7_SRTSR0_X(x)\
	(((x) & GENMASK(31, 28)) >> 28)

#define HMATRIX2_MATRIX_SRTSR0_SRTOP6_SRTSR0(x)  (((x) << 24) & GENMASK(27, 24))
#define HMATRIX2_MATRIX_SRTSR0_SRTOP6_SRTSR0_M   GENMASK(27, 24)
#define HMATRIX2_MATRIX_SRTSR0_SRTOP6_SRTSR0_X(x)\
	(((x) & GENMASK(27, 24)) >> 24)

#define HMATRIX2_MATRIX_SRTSR0_SRTOP5_SRTSR0(x)  (((x) << 20) & GENMASK(23, 20))
#define HMATRIX2_MATRIX_SRTSR0_SRTOP5_SRTSR0_M   GENMASK(23, 20)
#define HMATRIX2_MATRIX_SRTSR0_SRTOP5_SRTSR0_X(x)\
	(((x) & GENMASK(23, 20)) >> 20)

#define HMATRIX2_MATRIX_SRTSR0_SRTOP4_SRTSR0(x)  (((x) << 16) & GENMASK(19, 16))
#define HMATRIX2_MATRIX_SRTSR0_SRTOP4_SRTSR0_M   GENMASK(19, 16)
#define HMATRIX2_MATRIX_SRTSR0_SRTOP4_SRTSR0_X(x)\
	(((x) & GENMASK(19, 16)) >> 16)

#define HMATRIX2_MATRIX_SRTSR0_SRTOP3_SRTSR0(x)  (((x) << 12) & GENMASK(15, 12))
#define HMATRIX2_MATRIX_SRTSR0_SRTOP3_SRTSR0_M   GENMASK(15, 12)
#define HMATRIX2_MATRIX_SRTSR0_SRTOP3_SRTSR0_X(x)\
	(((x) & GENMASK(15, 12)) >> 12)

#define HMATRIX2_MATRIX_SRTSR0_SRTOP2_SRTSR0(x)  (((x) << 8) & GENMASK(11, 8))
#define HMATRIX2_MATRIX_SRTSR0_SRTOP2_SRTSR0_M   GENMASK(11, 8)
#define HMATRIX2_MATRIX_SRTSR0_SRTOP2_SRTSR0_X(x) (((x) & GENMASK(11, 8)) >> 8)

#define HMATRIX2_MATRIX_SRTSR0_SRTOP1_SRTSR0(x)  (((x) << 4) & GENMASK(7, 4))
#define HMATRIX2_MATRIX_SRTSR0_SRTOP1_SRTSR0_M   GENMASK(7, 4)
#define HMATRIX2_MATRIX_SRTSR0_SRTOP1_SRTSR0_X(x) (((x) & GENMASK(7, 4)) >> 4)

#define HMATRIX2_MATRIX_SRTSR0_SRTOP0_SRTSR0(x)  ((x) & GENMASK(3, 0))
#define HMATRIX2_MATRIX_SRTSR0_SRTOP0_SRTSR0_M   GENMASK(3, 0)
#define HMATRIX2_MATRIX_SRTSR0_SRTOP0_SRTSR0_X(x) ((x) & GENMASK(3, 0))

/*      TRNG:TRNG_REGS:TRNG_CR */
#define TRNG_TRNG_CR              0x00

#define TRNG_TRNG_CR_WAKEY(x)                    (((x) << 8) & GENMASK(31, 8))
#define TRNG_TRNG_CR_WAKEY_M                     GENMASK(31, 8)
#define TRNG_TRNG_CR_WAKEY_X(x)                  (((x) & GENMASK(31, 8)) >> 8)

#define TRNG_TRNG_CR_ENABLE(x)                   ((x) & GENMASK(0, 0))
#define TRNG_TRNG_CR_ENABLE_M                    GENMASK(0, 0)
#define TRNG_TRNG_CR_ENABLE_X(x)                 ((x) & GENMASK(0, 0))

/*      TRNG:TRNG_REGS:TRNG_MR */
#define TRNG_TRNG_MR              0x04

#define TRNG_TRNG_MR_HALFR(x)                    ((x) & GENMASK(0, 0))
#define TRNG_TRNG_MR_HALFR_M                     GENMASK(0, 0)
#define TRNG_TRNG_MR_HALFR_X(x)                  ((x) & GENMASK(0, 0))

/*      TRNG:TRNG_REGS:TRNG_PKBCR */
#define TRNG_TRNG_PKBCR           0x08

#define TRNG_TRNG_PKBCR_WAKEY_PKBCR(x)           (((x) << 16) & GENMASK(31, 16))
#define TRNG_TRNG_PKBCR_WAKEY_PKBCR_M            GENMASK(31, 16)
#define TRNG_TRNG_PKBCR_WAKEY_PKBCR_X(x)         (((x) & GENMASK(31, 16)) >> 16)

#define TRNG_TRNG_PKBCR_KLENGTH(x)               (((x) << 8) & GENMASK(15, 8))
#define TRNG_TRNG_PKBCR_KLENGTH_M                GENMASK(15, 8)
#define TRNG_TRNG_PKBCR_KLENGTH_X(x)             (((x) & GENMASK(15, 8)) >> 8)

#define TRNG_TRNG_PKBCR_KTARGET(x)               (((x) << 4) & GENMASK(5, 4))
#define TRNG_TRNG_PKBCR_KTARGET_M                GENMASK(5, 4)
#define TRNG_TRNG_PKBCR_KTARGET_X(x)             (((x) & GENMASK(5, 4)) >> 4)

#define TRNG_TRNG_PKBCR_KID(x)                   ((x) & GENMASK(0, 0))
#define TRNG_TRNG_PKBCR_KID_M                    GENMASK(0, 0)
#define TRNG_TRNG_PKBCR_KID_X(x)                 ((x) & GENMASK(0, 0))

/*      TRNG:TRNG_REGS:TRNG_IER */
#define TRNG_TRNG_IER             0x10

#define TRNG_TRNG_IER_EOTPKB(x)                  (((x) << 2) & GENMASK(2, 2))
#define TRNG_TRNG_IER_EOTPKB_M                   GENMASK(2, 2)
#define TRNG_TRNG_IER_EOTPKB_X(x)                (((x) & GENMASK(2, 2)) >> 2)

#define TRNG_TRNG_IER_SECE(x)                    (((x) << 1) & GENMASK(1, 1))
#define TRNG_TRNG_IER_SECE_M                     GENMASK(1, 1)
#define TRNG_TRNG_IER_SECE_X(x)                  (((x) & GENMASK(1, 1)) >> 1)

#define TRNG_TRNG_IER_DATRDY(x)                  ((x) & GENMASK(0, 0))
#define TRNG_TRNG_IER_DATRDY_M                   GENMASK(0, 0)
#define TRNG_TRNG_IER_DATRDY_X(x)                ((x) & GENMASK(0, 0))

/*      TRNG:TRNG_REGS:TRNG_IDR */
#define TRNG_TRNG_IDR             0x14

#define TRNG_TRNG_IDR_EOTPKB_IDR(x)              (((x) << 2) & GENMASK(2, 2))
#define TRNG_TRNG_IDR_EOTPKB_IDR_M               GENMASK(2, 2)
#define TRNG_TRNG_IDR_EOTPKB_IDR_X(x)            (((x) & GENMASK(2, 2)) >> 2)

#define TRNG_TRNG_IDR_SECE_IDR(x)                (((x) << 1) & GENMASK(1, 1))
#define TRNG_TRNG_IDR_SECE_IDR_M                 GENMASK(1, 1)
#define TRNG_TRNG_IDR_SECE_IDR_X(x)              (((x) & GENMASK(1, 1)) >> 1)

#define TRNG_TRNG_IDR_DATRDY_IDR(x)              ((x) & GENMASK(0, 0))
#define TRNG_TRNG_IDR_DATRDY_IDR_M               GENMASK(0, 0)
#define TRNG_TRNG_IDR_DATRDY_IDR_X(x)            ((x) & GENMASK(0, 0))

/*      TRNG:TRNG_REGS:TRNG_IMR */
#define TRNG_TRNG_IMR             0x18

#define TRNG_TRNG_IMR_EOTPKB_IMR(x)              (((x) << 2) & GENMASK(2, 2))
#define TRNG_TRNG_IMR_EOTPKB_IMR_M               GENMASK(2, 2)
#define TRNG_TRNG_IMR_EOTPKB_IMR_X(x)            (((x) & GENMASK(2, 2)) >> 2)

#define TRNG_TRNG_IMR_SECE_IMR(x)                (((x) << 1) & GENMASK(1, 1))
#define TRNG_TRNG_IMR_SECE_IMR_M                 GENMASK(1, 1)
#define TRNG_TRNG_IMR_SECE_IMR_X(x)              (((x) & GENMASK(1, 1)) >> 1)

#define TRNG_TRNG_IMR_DATRDY_IMR(x)              ((x) & GENMASK(0, 0))
#define TRNG_TRNG_IMR_DATRDY_IMR_M               GENMASK(0, 0)
#define TRNG_TRNG_IMR_DATRDY_IMR_X(x)            ((x) & GENMASK(0, 0))

/*      TRNG:TRNG_REGS:TRNG_ISR */
#define TRNG_TRNG_ISR             0x1c

#define TRNG_TRNG_ISR_EOTPKB_ISR(x)              (((x) << 2) & GENMASK(2, 2))
#define TRNG_TRNG_ISR_EOTPKB_ISR_M               GENMASK(2, 2)
#define TRNG_TRNG_ISR_EOTPKB_ISR_X(x)            (((x) & GENMASK(2, 2)) >> 2)

#define TRNG_TRNG_ISR_SECE_ISR(x)                (((x) << 1) & GENMASK(1, 1))
#define TRNG_TRNG_ISR_SECE_ISR_M                 GENMASK(1, 1)
#define TRNG_TRNG_ISR_SECE_ISR_X(x)              (((x) & GENMASK(1, 1)) >> 1)

#define TRNG_TRNG_ISR_DATRDY_ISR(x)              ((x) & GENMASK(0, 0))
#define TRNG_TRNG_ISR_DATRDY_ISR_M               GENMASK(0, 0)
#define TRNG_TRNG_ISR_DATRDY_ISR_X(x)            ((x) & GENMASK(0, 0))

/*      TRNG:TRNG_REGS:TRNG_ODATA */
#define TRNG_TRNG_ODATA           0x50

/*      TRNG:TRNG_REGS:TRNG_WPMR */
#define TRNG_TRNG_WPMR            0xe4

#define TRNG_TRNG_WPMR_WPKEY(x)                  (((x) << 8) & GENMASK(31, 8))
#define TRNG_TRNG_WPMR_WPKEY_M                   GENMASK(31, 8)
#define TRNG_TRNG_WPMR_WPKEY_X(x)                (((x) & GENMASK(31, 8)) >> 8)

#define TRNG_TRNG_WPMR_FIRSTE(x)                 (((x) << 4) & GENMASK(4, 4))
#define TRNG_TRNG_WPMR_FIRSTE_M                  GENMASK(4, 4)
#define TRNG_TRNG_WPMR_FIRSTE_X(x)               (((x) & GENMASK(4, 4)) >> 4)

#define TRNG_TRNG_WPMR_WPCREN(x)                 (((x) << 2) & GENMASK(2, 2))
#define TRNG_TRNG_WPMR_WPCREN_M                  GENMASK(2, 2)
#define TRNG_TRNG_WPMR_WPCREN_X(x)               (((x) & GENMASK(2, 2)) >> 2)

#define TRNG_TRNG_WPMR_WPITEN(x)                 (((x) << 1) & GENMASK(1, 1))
#define TRNG_TRNG_WPMR_WPITEN_M                  GENMASK(1, 1)
#define TRNG_TRNG_WPMR_WPITEN_X(x)               (((x) & GENMASK(1, 1)) >> 1)

#define TRNG_TRNG_WPMR_WPEN(x)                   ((x) & GENMASK(0, 0))
#define TRNG_TRNG_WPMR_WPEN_M                    GENMASK(0, 0)
#define TRNG_TRNG_WPMR_WPEN_X(x)                 ((x) & GENMASK(0, 0))

/*      TRNG:TRNG_REGS:TRNG_WPSR */
#define TRNG_TRNG_WPSR            0xe8

#define TRNG_TRNG_WPSR_ECLASS(x)                 (((x) << 31) & GENMASK(31, 31))
#define TRNG_TRNG_WPSR_ECLASS_M                  GENMASK(31, 31)
#define TRNG_TRNG_WPSR_ECLASS_X(x)               (((x) & GENMASK(31, 31)) >> 31)

#define TRNG_TRNG_WPSR_SWETYP(x)                 (((x) << 24) & GENMASK(27, 24))
#define TRNG_TRNG_WPSR_SWETYP_M                  GENMASK(27, 24)
#define TRNG_TRNG_WPSR_SWETYP_X(x)               (((x) & GENMASK(27, 24)) >> 24)

#define TRNG_TRNG_WPSR_WPVSRC(x)                 (((x) << 8) & GENMASK(23, 8))
#define TRNG_TRNG_WPSR_WPVSRC_M                  GENMASK(23, 8)
#define TRNG_TRNG_WPSR_WPVSRC_X(x)               (((x) & GENMASK(23, 8)) >> 8)

#define TRNG_TRNG_WPSR_SWE(x)                    (((x) << 3) & GENMASK(3, 3))
#define TRNG_TRNG_WPSR_SWE_M                     GENMASK(3, 3)
#define TRNG_TRNG_WPSR_SWE_X(x)                  (((x) & GENMASK(3, 3)) >> 3)

#define TRNG_TRNG_WPSR_SEQE(x)                   (((x) << 2) & GENMASK(2, 2))
#define TRNG_TRNG_WPSR_SEQE_M                    GENMASK(2, 2)
#define TRNG_TRNG_WPSR_SEQE_X(x)                 (((x) & GENMASK(2, 2)) >> 2)

#define TRNG_TRNG_WPSR_CGD(x)                    (((x) << 1) & GENMASK(1, 1))
#define TRNG_TRNG_WPSR_CGD_M                     GENMASK(1, 1)
#define TRNG_TRNG_WPSR_CGD_X(x)                  (((x) & GENMASK(1, 1)) >> 1)

#define TRNG_TRNG_WPSR_WPVS(x)                   ((x) & GENMASK(0, 0))
#define TRNG_TRNG_WPSR_WPVS_M                    GENMASK(0, 0)
#define TRNG_TRNG_WPSR_WPVS_X(x)                 ((x) & GENMASK(0, 0))

/*      TRNG:TRNG_REGS:TRNG_VERSION */
#define TRNG_TRNG_VERSION         0xfc

#define TRNG_TRNG_VERSION_MFN(x)                 (((x) << 16) & GENMASK(18, 16))
#define TRNG_TRNG_VERSION_MFN_M                  GENMASK(18, 16)
#define TRNG_TRNG_VERSION_MFN_X(x)               (((x) & GENMASK(18, 16)) >> 16)

#define TRNG_TRNG_VERSION_VERSION(x)             ((x) & GENMASK(11, 0))
#define TRNG_TRNG_VERSION_VERSION_M              GENMASK(11, 0)
#define TRNG_TRNG_VERSION_VERSION_X(x)           ((x) & GENMASK(11, 0))

/*      TZAESBNS:TZAESB_REGS:TZAESB_CR */
#define TZAESBNS_TZAESB_CR        0x00

#define TZAESBNS_TZAESB_CR_UNLOCK(x)             (((x) << 24) & GENMASK(24, 24))
#define TZAESBNS_TZAESB_CR_UNLOCK_M              GENMASK(24, 24)
#define TZAESBNS_TZAESB_CR_UNLOCK_X(x)           (((x) & GENMASK(24, 24)) >> 24)

#define TZAESBNS_TZAESB_CR_LOADSEED(x)           (((x) << 16) & GENMASK(16, 16))
#define TZAESBNS_TZAESB_CR_LOADSEED_M            GENMASK(16, 16)
#define TZAESBNS_TZAESB_CR_LOADSEED_X(x)         (((x) & GENMASK(16, 16)) >> 16)

#define TZAESBNS_TZAESB_CR_SWRST(x)              (((x) << 8) & GENMASK(8, 8))
#define TZAESBNS_TZAESB_CR_SWRST_M               GENMASK(8, 8)
#define TZAESBNS_TZAESB_CR_SWRST_X(x)            (((x) & GENMASK(8, 8)) >> 8)

#define TZAESBNS_TZAESB_CR_START(x)              ((x) & GENMASK(0, 0))
#define TZAESBNS_TZAESB_CR_START_M               GENMASK(0, 0)
#define TZAESBNS_TZAESB_CR_START_X(x)            ((x) & GENMASK(0, 0))

/*      TZAESBNS:TZAESB_REGS:TZAESB_MR */
#define TZAESBNS_TZAESB_MR        0x04

#define TZAESBNS_TZAESB_MR_TAMPCLR(x)            (((x) << 31) & GENMASK(31, 31))
#define TZAESBNS_TZAESB_MR_TAMPCLR_M             GENMASK(31, 31)
#define TZAESBNS_TZAESB_MR_TAMPCLR_X(x)          (((x) & GENMASK(31, 31)) >> 31)

#define TZAESBNS_TZAESB_MR_CMTYP7(x)             (((x) << 30) & GENMASK(30, 30))
#define TZAESBNS_TZAESB_MR_CMTYP7_M              GENMASK(30, 30)
#define TZAESBNS_TZAESB_MR_CMTYP7_X(x)           (((x) & GENMASK(30, 30)) >> 30)

#define TZAESBNS_TZAESB_MR_CMTYP6(x)             (((x) << 29) & GENMASK(29, 29))
#define TZAESBNS_TZAESB_MR_CMTYP6_M              GENMASK(29, 29)
#define TZAESBNS_TZAESB_MR_CMTYP6_X(x)           (((x) & GENMASK(29, 29)) >> 29)

#define TZAESBNS_TZAESB_MR_CMTYP5(x)             (((x) << 28) & GENMASK(28, 28))
#define TZAESBNS_TZAESB_MR_CMTYP5_M              GENMASK(28, 28)
#define TZAESBNS_TZAESB_MR_CMTYP5_X(x)           (((x) & GENMASK(28, 28)) >> 28)

#define TZAESBNS_TZAESB_MR_CMTYP4(x)             (((x) << 27) & GENMASK(27, 27))
#define TZAESBNS_TZAESB_MR_CMTYP4_M              GENMASK(27, 27)
#define TZAESBNS_TZAESB_MR_CMTYP4_X(x)           (((x) & GENMASK(27, 27)) >> 27)

#define TZAESBNS_TZAESB_MR_CMTYP3(x)             (((x) << 26) & GENMASK(26, 26))
#define TZAESBNS_TZAESB_MR_CMTYP3_M              GENMASK(26, 26)
#define TZAESBNS_TZAESB_MR_CMTYP3_X(x)           (((x) & GENMASK(26, 26)) >> 26)

#define TZAESBNS_TZAESB_MR_CMTYP2(x)             (((x) << 25) & GENMASK(25, 25))
#define TZAESBNS_TZAESB_MR_CMTYP2_M              GENMASK(25, 25)
#define TZAESBNS_TZAESB_MR_CMTYP2_X(x)           (((x) & GENMASK(25, 25)) >> 25)

#define TZAESBNS_TZAESB_MR_CMTYP1(x)             (((x) << 24) & GENMASK(24, 24))
#define TZAESBNS_TZAESB_MR_CMTYP1_M              GENMASK(24, 24)
#define TZAESBNS_TZAESB_MR_CMTYP1_X(x)           (((x) & GENMASK(24, 24)) >> 24)

#define TZAESBNS_TZAESB_MR_CKEY(x)               (((x) << 20) & GENMASK(23, 20))
#define TZAESBNS_TZAESB_MR_CKEY_M                GENMASK(23, 20)
#define TZAESBNS_TZAESB_MR_CKEY_X(x)             (((x) & GENMASK(23, 20)) >> 20)

#define TZAESBNS_TZAESB_MR_OPMOD(x)              (((x) << 12) & GENMASK(14, 12))
#define TZAESBNS_TZAESB_MR_OPMOD_M               GENMASK(14, 12)
#define TZAESBNS_TZAESB_MR_OPMOD_X(x)            (((x) & GENMASK(14, 12)) >> 12)

#define TZAESBNS_TZAESB_MR_PROCDLY(x)            (((x) << 4) & GENMASK(7, 4))
#define TZAESBNS_TZAESB_MR_PROCDLY_M             GENMASK(7, 4)
#define TZAESBNS_TZAESB_MR_PROCDLY_X(x)          (((x) & GENMASK(7, 4)) >> 4)

#define TZAESBNS_TZAESB_MR_DUALBUFF(x)           (((x) << 3) & GENMASK(3, 3))
#define TZAESBNS_TZAESB_MR_DUALBUFF_M            GENMASK(3, 3)
#define TZAESBNS_TZAESB_MR_DUALBUFF_X(x)         (((x) & GENMASK(3, 3)) >> 3)

#define TZAESBNS_TZAESB_MR_AAHB(x)               (((x) << 2) & GENMASK(2, 2))
#define TZAESBNS_TZAESB_MR_AAHB_M                GENMASK(2, 2)
#define TZAESBNS_TZAESB_MR_AAHB_X(x)             (((x) & GENMASK(2, 2)) >> 2)

/*      TZAESBNS:TZAESB_REGS:TZAESB_IER */
#define TZAESBNS_TZAESB_IER       0x10

#define TZAESBNS_TZAESB_IER_SECE(x)              (((x) << 19) & GENMASK(19, 19))
#define TZAESBNS_TZAESB_IER_SECE_M               GENMASK(19, 19)
#define TZAESBNS_TZAESB_IER_SECE_X(x)            (((x) & GENMASK(19, 19)) >> 19)

#define TZAESBNS_TZAESB_IER_URAD(x)              (((x) << 8) & GENMASK(8, 8))
#define TZAESBNS_TZAESB_IER_URAD_M               GENMASK(8, 8)
#define TZAESBNS_TZAESB_IER_URAD_X(x)            (((x) & GENMASK(8, 8)) >> 8)

/*      TZAESBNS:TZAESB_REGS:TZAESB_IDR */
#define TZAESBNS_TZAESB_IDR       0x14

#define TZAESBNS_TZAESB_IDR_SECE_IDR(x)          (((x) << 19) & GENMASK(19, 19))
#define TZAESBNS_TZAESB_IDR_SECE_IDR_M           GENMASK(19, 19)
#define TZAESBNS_TZAESB_IDR_SECE_IDR_X(x)        (((x) & GENMASK(19, 19)) >> 19)

#define TZAESBNS_TZAESB_IDR_URAD_IDR(x)          (((x) << 8) & GENMASK(8, 8))
#define TZAESBNS_TZAESB_IDR_URAD_IDR_M           GENMASK(8, 8)
#define TZAESBNS_TZAESB_IDR_URAD_IDR_X(x)        (((x) & GENMASK(8, 8)) >> 8)

/*      TZAESBNS:TZAESB_REGS:TZAESB_IMR */
#define TZAESBNS_TZAESB_IMR       0x18

#define TZAESBNS_TZAESB_IMR_SECE_IMR(x)          (((x) << 19) & GENMASK(19, 19))
#define TZAESBNS_TZAESB_IMR_SECE_IMR_M           GENMASK(19, 19)
#define TZAESBNS_TZAESB_IMR_SECE_IMR_X(x)        (((x) & GENMASK(19, 19)) >> 19)

#define TZAESBNS_TZAESB_IMR_URAD_IMR(x)          (((x) << 8) & GENMASK(8, 8))
#define TZAESBNS_TZAESB_IMR_URAD_IMR_M           GENMASK(8, 8)
#define TZAESBNS_TZAESB_IMR_URAD_IMR_X(x)        (((x) & GENMASK(8, 8)) >> 8)

/*      TZAESBNS:TZAESB_REGS:TZAESB_ISR */
#define TZAESBNS_TZAESB_ISR       0x1c

#define TZAESBNS_TZAESB_ISR_SECE_ISR(x)          (((x) << 19) & GENMASK(19, 19))
#define TZAESBNS_TZAESB_ISR_SECE_ISR_M           GENMASK(19, 19)
#define TZAESBNS_TZAESB_ISR_SECE_ISR_X(x)        (((x) & GENMASK(19, 19)) >> 19)

#define TZAESBNS_TZAESB_ISR_URAT_ISR(x)          (((x) << 12) & GENMASK(15, 12))
#define TZAESBNS_TZAESB_ISR_URAT_ISR_M           GENMASK(15, 12)
#define TZAESBNS_TZAESB_ISR_URAT_ISR_X(x)        (((x) & GENMASK(15, 12)) >> 12)

#define TZAESBNS_TZAESB_ISR_URAD_ISR(x)          (((x) << 8) & GENMASK(8, 8))
#define TZAESBNS_TZAESB_ISR_URAD_ISR_M           GENMASK(8, 8)
#define TZAESBNS_TZAESB_ISR_URAD_ISR_X(x)        (((x) & GENMASK(8, 8)) >> 8)

/*      TZAESBNS:TZAESB_REGS:TZAESB_KEYWR0 */
#define TZAESBNS_TZAESB_KEYWR0    0x20

/*      TZAESBNS:TZAESB_REGS:TZAESB_KEYWR1 */
#define TZAESBNS_TZAESB_KEYWR1    0x24

/*      TZAESBNS:TZAESB_REGS:TZAESB_KEYWR2 */
#define TZAESBNS_TZAESB_KEYWR2    0x28

/*      TZAESBNS:TZAESB_REGS:TZAESB_KEYWR3 */
#define TZAESBNS_TZAESB_KEYWR3    0x2c

/*      TZAESBNS:TZAESB_REGS:TZAESB_IVR0 */
#define TZAESBNS_TZAESB_IVR0      0x60

/*      TZAESBNS:TZAESB_REGS:TZAESB_IVR1 */
#define TZAESBNS_TZAESB_IVR1      0x64

/*      TZAESBNS:TZAESB_REGS:TZAESB_IVR2 */
#define TZAESBNS_TZAESB_IVR2      0x68

/*      TZAESBNS:TZAESB_REGS:TZAESB_IVR3 */
#define TZAESBNS_TZAESB_IVR3      0x6c

/*      TZAESBNS:TZAESB_REGS:TZAESB_EMR */
#define TZAESBNS_TZAESB_EMR       0xb0

#define TZAESBNS_TZAESB_EMR_PKRS(x)              (((x) << 7) & GENMASK(7, 7))
#define TZAESBNS_TZAESB_EMR_PKRS_M               GENMASK(7, 7)
#define TZAESBNS_TZAESB_EMR_PKRS_X(x)            (((x) & GENMASK(7, 7)) >> 7)

#define TZAESBNS_TZAESB_EMR_PKWO(x)              (((x) << 6) & GENMASK(6, 6))
#define TZAESBNS_TZAESB_EMR_PKWO_M               GENMASK(6, 6)
#define TZAESBNS_TZAESB_EMR_PKWO_X(x)            (((x) & GENMASK(6, 6)) >> 6)

/*      TZAESBNS:TZAESB_REGS:TZAESB_WPMR */
#define TZAESBNS_TZAESB_WPMR      0xe4

#define TZAESBNS_TZAESB_WPMR_WPKEY(x)            (((x) << 8) & GENMASK(31, 8))
#define TZAESBNS_TZAESB_WPMR_WPKEY_M             GENMASK(31, 8)
#define TZAESBNS_TZAESB_WPMR_WPKEY_X(x)          (((x) & GENMASK(31, 8)) >> 8)

#define TZAESBNS_TZAESB_WPMR_ACTION(x)           (((x) << 5) & GENMASK(7, 5))
#define TZAESBNS_TZAESB_WPMR_ACTION_M            GENMASK(7, 5)
#define TZAESBNS_TZAESB_WPMR_ACTION_X(x)         (((x) & GENMASK(7, 5)) >> 5)

#define TZAESBNS_TZAESB_WPMR_FIRSTE(x)           (((x) << 4) & GENMASK(4, 4))
#define TZAESBNS_TZAESB_WPMR_FIRSTE_M            GENMASK(4, 4)
#define TZAESBNS_TZAESB_WPMR_FIRSTE_X(x)         (((x) & GENMASK(4, 4)) >> 4)

#define TZAESBNS_TZAESB_WPMR_WPCREN(x)           (((x) << 2) & GENMASK(2, 2))
#define TZAESBNS_TZAESB_WPMR_WPCREN_M            GENMASK(2, 2)
#define TZAESBNS_TZAESB_WPMR_WPCREN_X(x)         (((x) & GENMASK(2, 2)) >> 2)

#define TZAESBNS_TZAESB_WPMR_WPITEN(x)           (((x) << 1) & GENMASK(1, 1))
#define TZAESBNS_TZAESB_WPMR_WPITEN_M            GENMASK(1, 1)
#define TZAESBNS_TZAESB_WPMR_WPITEN_X(x)         (((x) & GENMASK(1, 1)) >> 1)

#define TZAESBNS_TZAESB_WPMR_WPEN(x)             ((x) & GENMASK(0, 0))
#define TZAESBNS_TZAESB_WPMR_WPEN_M              GENMASK(0, 0)
#define TZAESBNS_TZAESB_WPMR_WPEN_X(x)           ((x) & GENMASK(0, 0))

/*      TZAESBNS:TZAESB_REGS:TZAESB_WPSR */
#define TZAESBNS_TZAESB_WPSR      0xe8

#define TZAESBNS_TZAESB_WPSR_ECLASS(x)           (((x) << 31) & GENMASK(31, 31))
#define TZAESBNS_TZAESB_WPSR_ECLASS_M            GENMASK(31, 31)
#define TZAESBNS_TZAESB_WPSR_ECLASS_X(x)         (((x) & GENMASK(31, 31)) >> 31)

#define TZAESBNS_TZAESB_WPSR_SWETYP(x)           (((x) << 24) & GENMASK(27, 24))
#define TZAESBNS_TZAESB_WPSR_SWETYP_M            GENMASK(27, 24)
#define TZAESBNS_TZAESB_WPSR_SWETYP_X(x)         (((x) & GENMASK(27, 24)) >> 24)

#define TZAESBNS_TZAESB_WPSR_WPVSRC(x)           (((x) << 8) & GENMASK(15, 8))
#define TZAESBNS_TZAESB_WPSR_WPVSRC_M            GENMASK(15, 8)
#define TZAESBNS_TZAESB_WPSR_WPVSRC_X(x)         (((x) & GENMASK(15, 8)) >> 8)

#define TZAESBNS_TZAESB_WPSR_PKRPVS(x)           (((x) << 4) & GENMASK(4, 4))
#define TZAESBNS_TZAESB_WPSR_PKRPVS_M            GENMASK(4, 4)
#define TZAESBNS_TZAESB_WPSR_PKRPVS_X(x)         (((x) & GENMASK(4, 4)) >> 4)

#define TZAESBNS_TZAESB_WPSR_SWE(x)              (((x) << 3) & GENMASK(3, 3))
#define TZAESBNS_TZAESB_WPSR_SWE_M               GENMASK(3, 3)
#define TZAESBNS_TZAESB_WPSR_SWE_X(x)            (((x) & GENMASK(3, 3)) >> 3)

#define TZAESBNS_TZAESB_WPSR_SEQE(x)             (((x) << 2) & GENMASK(2, 2))
#define TZAESBNS_TZAESB_WPSR_SEQE_M              GENMASK(2, 2)
#define TZAESBNS_TZAESB_WPSR_SEQE_X(x)           (((x) & GENMASK(2, 2)) >> 2)

#define TZAESBNS_TZAESB_WPSR_CGD(x)              (((x) << 1) & GENMASK(1, 1))
#define TZAESBNS_TZAESB_WPSR_CGD_M               GENMASK(1, 1)
#define TZAESBNS_TZAESB_WPSR_CGD_X(x)            (((x) & GENMASK(1, 1)) >> 1)

#define TZAESBNS_TZAESB_WPSR_WPVS(x)             ((x) & GENMASK(0, 0))
#define TZAESBNS_TZAESB_WPSR_WPVS_M              GENMASK(0, 0)
#define TZAESBNS_TZAESB_WPSR_WPVS_X(x)           ((x) & GENMASK(0, 0))

/*      TZAESBNS:TZAESB_REGS:TZAESB_VERSION */
#define TZAESBNS_TZAESB_VERSION   0xfc

#define TZAESBNS_TZAESB_VERSION_MFN(x)           (((x) << 16) & GENMASK(18, 16))
#define TZAESBNS_TZAESB_VERSION_MFN_M            GENMASK(18, 16)
#define TZAESBNS_TZAESB_VERSION_MFN_X(x)         (((x) & GENMASK(18, 16)) >> 16)

#define TZAESBNS_TZAESB_VERSION_VERSION(x)       ((x) & GENMASK(11, 0))
#define TZAESBNS_TZAESB_VERSION_VERSION_M        GENMASK(11, 0)
#define TZAESBNS_TZAESB_VERSION_VERSION_X(x)     ((x) & GENMASK(11, 0))

/*      TZAESBS:TZAESB_REGS:TZAESB_CR */
#define TZAESBS_TZAESB_CR         0x00

#define TZAESBS_TZAESB_CR_UNLOCK(x)              (((x) << 24) & GENMASK(24, 24))
#define TZAESBS_TZAESB_CR_UNLOCK_M               GENMASK(24, 24)
#define TZAESBS_TZAESB_CR_UNLOCK_X(x)            (((x) & GENMASK(24, 24)) >> 24)

#define TZAESBS_TZAESB_CR_LOADSEED(x)            (((x) << 16) & GENMASK(16, 16))
#define TZAESBS_TZAESB_CR_LOADSEED_M             GENMASK(16, 16)
#define TZAESBS_TZAESB_CR_LOADSEED_X(x)          (((x) & GENMASK(16, 16)) >> 16)

#define TZAESBS_TZAESB_CR_SWRST(x)               (((x) << 8) & GENMASK(8, 8))
#define TZAESBS_TZAESB_CR_SWRST_M                GENMASK(8, 8)
#define TZAESBS_TZAESB_CR_SWRST_X(x)             (((x) & GENMASK(8, 8)) >> 8)

#define TZAESBS_TZAESB_CR_START(x)               ((x) & GENMASK(0, 0))
#define TZAESBS_TZAESB_CR_START_M                GENMASK(0, 0)
#define TZAESBS_TZAESB_CR_START_X(x)             ((x) & GENMASK(0, 0))

/*      TZAESBS:TZAESB_REGS:TZAESB_MR */
#define TZAESBS_TZAESB_MR         0x04

#define TZAESBS_TZAESB_MR_TAMPCLR(x)             (((x) << 31) & GENMASK(31, 31))
#define TZAESBS_TZAESB_MR_TAMPCLR_M              GENMASK(31, 31)
#define TZAESBS_TZAESB_MR_TAMPCLR_X(x)           (((x) & GENMASK(31, 31)) >> 31)

#define TZAESBS_TZAESB_MR_CMTYP7(x)              (((x) << 30) & GENMASK(30, 30))
#define TZAESBS_TZAESB_MR_CMTYP7_M               GENMASK(30, 30)
#define TZAESBS_TZAESB_MR_CMTYP7_X(x)            (((x) & GENMASK(30, 30)) >> 30)

#define TZAESBS_TZAESB_MR_CMTYP6(x)              (((x) << 29) & GENMASK(29, 29))
#define TZAESBS_TZAESB_MR_CMTYP6_M               GENMASK(29, 29)
#define TZAESBS_TZAESB_MR_CMTYP6_X(x)            (((x) & GENMASK(29, 29)) >> 29)

#define TZAESBS_TZAESB_MR_CMTYP5(x)              (((x) << 28) & GENMASK(28, 28))
#define TZAESBS_TZAESB_MR_CMTYP5_M               GENMASK(28, 28)
#define TZAESBS_TZAESB_MR_CMTYP5_X(x)            (((x) & GENMASK(28, 28)) >> 28)

#define TZAESBS_TZAESB_MR_CMTYP4(x)              (((x) << 27) & GENMASK(27, 27))
#define TZAESBS_TZAESB_MR_CMTYP4_M               GENMASK(27, 27)
#define TZAESBS_TZAESB_MR_CMTYP4_X(x)            (((x) & GENMASK(27, 27)) >> 27)

#define TZAESBS_TZAESB_MR_CMTYP3(x)              (((x) << 26) & GENMASK(26, 26))
#define TZAESBS_TZAESB_MR_CMTYP3_M               GENMASK(26, 26)
#define TZAESBS_TZAESB_MR_CMTYP3_X(x)            (((x) & GENMASK(26, 26)) >> 26)

#define TZAESBS_TZAESB_MR_CMTYP2(x)              (((x) << 25) & GENMASK(25, 25))
#define TZAESBS_TZAESB_MR_CMTYP2_M               GENMASK(25, 25)
#define TZAESBS_TZAESB_MR_CMTYP2_X(x)            (((x) & GENMASK(25, 25)) >> 25)

#define TZAESBS_TZAESB_MR_CMTYP1(x)              (((x) << 24) & GENMASK(24, 24))
#define TZAESBS_TZAESB_MR_CMTYP1_M               GENMASK(24, 24)
#define TZAESBS_TZAESB_MR_CMTYP1_X(x)            (((x) & GENMASK(24, 24)) >> 24)

#define TZAESBS_TZAESB_MR_CKEY(x)                (((x) << 20) & GENMASK(23, 20))
#define TZAESBS_TZAESB_MR_CKEY_M                 GENMASK(23, 20)
#define TZAESBS_TZAESB_MR_CKEY_X(x)              (((x) & GENMASK(23, 20)) >> 20)

#define TZAESBS_TZAESB_MR_OPMOD(x)               (((x) << 12) & GENMASK(14, 12))
#define TZAESBS_TZAESB_MR_OPMOD_M                GENMASK(14, 12)
#define TZAESBS_TZAESB_MR_OPMOD_X(x)             (((x) & GENMASK(14, 12)) >> 12)

#define TZAESBS_TZAESB_MR_PROCDLY(x)             (((x) << 4) & GENMASK(7, 4))
#define TZAESBS_TZAESB_MR_PROCDLY_M              GENMASK(7, 4)
#define TZAESBS_TZAESB_MR_PROCDLY_X(x)           (((x) & GENMASK(7, 4)) >> 4)

#define TZAESBS_TZAESB_MR_DUALBUFF(x)            (((x) << 3) & GENMASK(3, 3))
#define TZAESBS_TZAESB_MR_DUALBUFF_M             GENMASK(3, 3)
#define TZAESBS_TZAESB_MR_DUALBUFF_X(x)          (((x) & GENMASK(3, 3)) >> 3)

#define TZAESBS_TZAESB_MR_AAHB(x)                (((x) << 2) & GENMASK(2, 2))
#define TZAESBS_TZAESB_MR_AAHB_M                 GENMASK(2, 2)
#define TZAESBS_TZAESB_MR_AAHB_X(x)              (((x) & GENMASK(2, 2)) >> 2)

/*      TZAESBS:TZAESB_REGS:TZAESB_IER */
#define TZAESBS_TZAESB_IER        0x10

#define TZAESBS_TZAESB_IER_SECE(x)               (((x) << 19) & GENMASK(19, 19))
#define TZAESBS_TZAESB_IER_SECE_M                GENMASK(19, 19)
#define TZAESBS_TZAESB_IER_SECE_X(x)             (((x) & GENMASK(19, 19)) >> 19)

#define TZAESBS_TZAESB_IER_URAD(x)               (((x) << 8) & GENMASK(8, 8))
#define TZAESBS_TZAESB_IER_URAD_M                GENMASK(8, 8)
#define TZAESBS_TZAESB_IER_URAD_X(x)             (((x) & GENMASK(8, 8)) >> 8)

/*      TZAESBS:TZAESB_REGS:TZAESB_IDR */
#define TZAESBS_TZAESB_IDR        0x14

#define TZAESBS_TZAESB_IDR_SECE_IDR(x)           (((x) << 19) & GENMASK(19, 19))
#define TZAESBS_TZAESB_IDR_SECE_IDR_M            GENMASK(19, 19)
#define TZAESBS_TZAESB_IDR_SECE_IDR_X(x)         (((x) & GENMASK(19, 19)) >> 19)

#define TZAESBS_TZAESB_IDR_URAD_IDR(x)           (((x) << 8) & GENMASK(8, 8))
#define TZAESBS_TZAESB_IDR_URAD_IDR_M            GENMASK(8, 8)
#define TZAESBS_TZAESB_IDR_URAD_IDR_X(x)         (((x) & GENMASK(8, 8)) >> 8)

/*      TZAESBS:TZAESB_REGS:TZAESB_IMR */
#define TZAESBS_TZAESB_IMR        0x18

#define TZAESBS_TZAESB_IMR_SECE_IMR(x)           (((x) << 19) & GENMASK(19, 19))
#define TZAESBS_TZAESB_IMR_SECE_IMR_M            GENMASK(19, 19)
#define TZAESBS_TZAESB_IMR_SECE_IMR_X(x)         (((x) & GENMASK(19, 19)) >> 19)

#define TZAESBS_TZAESB_IMR_URAD_IMR(x)           (((x) << 8) & GENMASK(8, 8))
#define TZAESBS_TZAESB_IMR_URAD_IMR_M            GENMASK(8, 8)
#define TZAESBS_TZAESB_IMR_URAD_IMR_X(x)         (((x) & GENMASK(8, 8)) >> 8)

/*      TZAESBS:TZAESB_REGS:TZAESB_ISR */
#define TZAESBS_TZAESB_ISR        0x1c

#define TZAESBS_TZAESB_ISR_SECE_ISR(x)           (((x) << 19) & GENMASK(19, 19))
#define TZAESBS_TZAESB_ISR_SECE_ISR_M            GENMASK(19, 19)
#define TZAESBS_TZAESB_ISR_SECE_ISR_X(x)         (((x) & GENMASK(19, 19)) >> 19)

#define TZAESBS_TZAESB_ISR_URAT_ISR(x)           (((x) << 12) & GENMASK(15, 12))
#define TZAESBS_TZAESB_ISR_URAT_ISR_M            GENMASK(15, 12)
#define TZAESBS_TZAESB_ISR_URAT_ISR_X(x)         (((x) & GENMASK(15, 12)) >> 12)

#define TZAESBS_TZAESB_ISR_URAD_ISR(x)           (((x) << 8) & GENMASK(8, 8))
#define TZAESBS_TZAESB_ISR_URAD_ISR_M            GENMASK(8, 8)
#define TZAESBS_TZAESB_ISR_URAD_ISR_X(x)         (((x) & GENMASK(8, 8)) >> 8)

/*      TZAESBS:TZAESB_REGS:TZAESB_KEYWR0 */
#define TZAESBS_TZAESB_KEYWR0     0x20

/*      TZAESBS:TZAESB_REGS:TZAESB_KEYWR1 */
#define TZAESBS_TZAESB_KEYWR1     0x24

/*      TZAESBS:TZAESB_REGS:TZAESB_KEYWR2 */
#define TZAESBS_TZAESB_KEYWR2     0x28

/*      TZAESBS:TZAESB_REGS:TZAESB_KEYWR3 */
#define TZAESBS_TZAESB_KEYWR3     0x2c

/*      TZAESBS:TZAESB_REGS:TZAESB_IVR0 */
#define TZAESBS_TZAESB_IVR0       0x60

/*      TZAESBS:TZAESB_REGS:TZAESB_IVR1 */
#define TZAESBS_TZAESB_IVR1       0x64

/*      TZAESBS:TZAESB_REGS:TZAESB_IVR2 */
#define TZAESBS_TZAESB_IVR2       0x68

/*      TZAESBS:TZAESB_REGS:TZAESB_IVR3 */
#define TZAESBS_TZAESB_IVR3       0x6c

/*      TZAESBS:TZAESB_REGS:TZAESB_EMR */
#define TZAESBS_TZAESB_EMR        0xb0

#define TZAESBS_TZAESB_EMR_PKRS(x)               (((x) << 7) & GENMASK(7, 7))
#define TZAESBS_TZAESB_EMR_PKRS_M                GENMASK(7, 7)
#define TZAESBS_TZAESB_EMR_PKRS_X(x)             (((x) & GENMASK(7, 7)) >> 7)

#define TZAESBS_TZAESB_EMR_PKWO(x)               (((x) << 6) & GENMASK(6, 6))
#define TZAESBS_TZAESB_EMR_PKWO_M                GENMASK(6, 6)
#define TZAESBS_TZAESB_EMR_PKWO_X(x)             (((x) & GENMASK(6, 6)) >> 6)

/*      TZAESBS:TZAESB_REGS:TZAESB_WPMR */
#define TZAESBS_TZAESB_WPMR       0xe4

#define TZAESBS_TZAESB_WPMR_WPKEY(x)             (((x) << 8) & GENMASK(31, 8))
#define TZAESBS_TZAESB_WPMR_WPKEY_M              GENMASK(31, 8)
#define TZAESBS_TZAESB_WPMR_WPKEY_X(x)           (((x) & GENMASK(31, 8)) >> 8)

#define TZAESBS_TZAESB_WPMR_ACTION(x)            (((x) << 5) & GENMASK(7, 5))
#define TZAESBS_TZAESB_WPMR_ACTION_M             GENMASK(7, 5)
#define TZAESBS_TZAESB_WPMR_ACTION_X(x)          (((x) & GENMASK(7, 5)) >> 5)

#define TZAESBS_TZAESB_WPMR_FIRSTE(x)            (((x) << 4) & GENMASK(4, 4))
#define TZAESBS_TZAESB_WPMR_FIRSTE_M             GENMASK(4, 4)
#define TZAESBS_TZAESB_WPMR_FIRSTE_X(x)          (((x) & GENMASK(4, 4)) >> 4)

#define TZAESBS_TZAESB_WPMR_WPCREN(x)            (((x) << 2) & GENMASK(2, 2))
#define TZAESBS_TZAESB_WPMR_WPCREN_M             GENMASK(2, 2)
#define TZAESBS_TZAESB_WPMR_WPCREN_X(x)          (((x) & GENMASK(2, 2)) >> 2)

#define TZAESBS_TZAESB_WPMR_WPITEN(x)            (((x) << 1) & GENMASK(1, 1))
#define TZAESBS_TZAESB_WPMR_WPITEN_M             GENMASK(1, 1)
#define TZAESBS_TZAESB_WPMR_WPITEN_X(x)          (((x) & GENMASK(1, 1)) >> 1)

#define TZAESBS_TZAESB_WPMR_WPEN(x)              ((x) & GENMASK(0, 0))
#define TZAESBS_TZAESB_WPMR_WPEN_M               GENMASK(0, 0)
#define TZAESBS_TZAESB_WPMR_WPEN_X(x)            ((x) & GENMASK(0, 0))

/*      TZAESBS:TZAESB_REGS:TZAESB_WPSR */
#define TZAESBS_TZAESB_WPSR       0xe8

#define TZAESBS_TZAESB_WPSR_ECLASS(x)            (((x) << 31) & GENMASK(31, 31))
#define TZAESBS_TZAESB_WPSR_ECLASS_M             GENMASK(31, 31)
#define TZAESBS_TZAESB_WPSR_ECLASS_X(x)          (((x) & GENMASK(31, 31)) >> 31)

#define TZAESBS_TZAESB_WPSR_SWETYP(x)            (((x) << 24) & GENMASK(27, 24))
#define TZAESBS_TZAESB_WPSR_SWETYP_M             GENMASK(27, 24)
#define TZAESBS_TZAESB_WPSR_SWETYP_X(x)          (((x) & GENMASK(27, 24)) >> 24)

#define TZAESBS_TZAESB_WPSR_WPVSRC(x)            (((x) << 8) & GENMASK(15, 8))
#define TZAESBS_TZAESB_WPSR_WPVSRC_M             GENMASK(15, 8)
#define TZAESBS_TZAESB_WPSR_WPVSRC_X(x)          (((x) & GENMASK(15, 8)) >> 8)

#define TZAESBS_TZAESB_WPSR_PKRPVS(x)            (((x) << 4) & GENMASK(4, 4))
#define TZAESBS_TZAESB_WPSR_PKRPVS_M             GENMASK(4, 4)
#define TZAESBS_TZAESB_WPSR_PKRPVS_X(x)          (((x) & GENMASK(4, 4)) >> 4)

#define TZAESBS_TZAESB_WPSR_SWE(x)               (((x) << 3) & GENMASK(3, 3))
#define TZAESBS_TZAESB_WPSR_SWE_M                GENMASK(3, 3)
#define TZAESBS_TZAESB_WPSR_SWE_X(x)             (((x) & GENMASK(3, 3)) >> 3)

#define TZAESBS_TZAESB_WPSR_SEQE(x)              (((x) << 2) & GENMASK(2, 2))
#define TZAESBS_TZAESB_WPSR_SEQE_M               GENMASK(2, 2)
#define TZAESBS_TZAESB_WPSR_SEQE_X(x)            (((x) & GENMASK(2, 2)) >> 2)

#define TZAESBS_TZAESB_WPSR_CGD(x)               (((x) << 1) & GENMASK(1, 1))
#define TZAESBS_TZAESB_WPSR_CGD_M                GENMASK(1, 1)
#define TZAESBS_TZAESB_WPSR_CGD_X(x)             (((x) & GENMASK(1, 1)) >> 1)

#define TZAESBS_TZAESB_WPSR_WPVS(x)              ((x) & GENMASK(0, 0))
#define TZAESBS_TZAESB_WPSR_WPVS_M               GENMASK(0, 0)
#define TZAESBS_TZAESB_WPSR_WPVS_X(x)            ((x) & GENMASK(0, 0))

/*      TZAESBS:TZAESB_REGS:TZAESB_VERSION */
#define TZAESBS_TZAESB_VERSION    0xfc

#define TZAESBS_TZAESB_VERSION_MFN(x)            (((x) << 16) & GENMASK(18, 16))
#define TZAESBS_TZAESB_VERSION_MFN_M             GENMASK(18, 16)
#define TZAESBS_TZAESB_VERSION_MFN_X(x)          (((x) & GENMASK(18, 16)) >> 16)

#define TZAESBS_TZAESB_VERSION_VERSION(x)        ((x) & GENMASK(11, 0))
#define TZAESBS_TZAESB_VERSION_VERSION_M         GENMASK(11, 0)
#define TZAESBS_TZAESB_VERSION_VERSION_X(x)      ((x) & GENMASK(11, 0))

/*      TZPM:TZPM_REGS:TZPM_EN */
#define TZPM_TZPM_EN              0x00

#define TZPM_TZPM_EN_TZPM_EN(x)                  ((x) & GENMASK(0, 0))
#define TZPM_TZPM_EN_TZPM_EN_M                   GENMASK(0, 0)
#define TZPM_TZPM_EN_TZPM_EN_X(x)                ((x) & GENMASK(0, 0))

/*      TZPM:TZPM_REGS:TZPM_KEY */
#define TZPM_TZPM_KEY             0x04

/*      TZPM:TZPM_REGS:TZPCTL0 */
#define TZPM_TZPCTL0              0x08

#define TZPM_TZPCTL0_QSPI2(x)                    (((x) << 13) & GENMASK(13, 13))
#define TZPM_TZPCTL0_QSPI2_M                     GENMASK(13, 13)
#define TZPM_TZPCTL0_QSPI2_X(x)                  (((x) & GENMASK(13, 13)) >> 13)

#define TZPM_TZPCTL0_SDMMC(x)                    (((x) << 12) & GENMASK(12, 12))
#define TZPM_TZPCTL0_SDMMC_M                     GENMASK(12, 12)
#define TZPM_TZPCTL0_SDMMC_X(x)                  (((x) & GENMASK(12, 12)) >> 12)

#define TZPM_TZPCTL0_TC1(x)                      (((x) << 9) & GENMASK(9, 9))
#define TZPM_TZPCTL0_TC1_M                       GENMASK(9, 9)
#define TZPM_TZPCTL0_TC1_X(x)                    (((x) & GENMASK(9, 9)) >> 9)

#define TZPM_TZPCTL0_MCAN1(x)                    (((x) << 8) & GENMASK(8, 8))
#define TZPM_TZPCTL0_MCAN1_M                     GENMASK(8, 8)
#define TZPM_TZPCTL0_MCAN1_X(x)                  (((x) & GENMASK(8, 8)) >> 8)

#define TZPM_TZPCTL0_MCAN0(x)                    (((x) << 7) & GENMASK(7, 7))
#define TZPM_TZPCTL0_MCAN0_M                     GENMASK(7, 7)
#define TZPM_TZPCTL0_MCAN0_X(x)                  (((x) & GENMASK(7, 7)) >> 7)

#define TZPM_TZPCTL0_TZAESBS(x)                  (((x) << 6) & GENMASK(6, 6))
#define TZPM_TZPCTL0_TZAESBS_M                   GENMASK(6, 6)
#define TZPM_TZPCTL0_TZAESBS_X(x)                (((x) & GENMASK(6, 6)) >> 6)

#define TZPM_TZPCTL0_TZAESBNS(x)                 (((x) << 5) & GENMASK(5, 5))
#define TZPM_TZPCTL0_TZAESBNS_M                  GENMASK(5, 5)
#define TZPM_TZPCTL0_TZAESBNS_X(x)               (((x) & GENMASK(5, 5)) >> 5)

#define TZPM_TZPCTL0_ICM(x)                      (((x) << 4) & GENMASK(4, 4))
#define TZPM_TZPCTL0_ICM_M                       GENMASK(4, 4)
#define TZPM_TZPCTL0_ICM_X(x)                    (((x) & GENMASK(4, 4)) >> 4)

#define TZPM_TZPCTL0_UDPHS0(x)                   (((x) << 2) & GENMASK(2, 2))
#define TZPM_TZPCTL0_UDPHS0_M                    GENMASK(2, 2)
#define TZPM_TZPCTL0_UDPHS0_X(x)                 (((x) & GENMASK(2, 2)) >> 2)

#define TZPM_TZPCTL0_QSPI0(x)                    (((x) << 1) & GENMASK(1, 1))
#define TZPM_TZPCTL0_QSPI0_M                     GENMASK(1, 1)
#define TZPM_TZPCTL0_QSPI0_X(x)                  (((x) & GENMASK(1, 1)) >> 1)

#define TZPM_TZPCTL0_HMATRIX(x)                  ((x) & GENMASK(0, 0))
#define TZPM_TZPCTL0_HMATRIX_M                   GENMASK(0, 0)
#define TZPM_TZPCTL0_HMATRIX_X(x)                ((x) & GENMASK(0, 0))

/*      TZPM:TZPM_REGS:TZPCTL1 */
#define TZPM_TZPCTL1              0x0c

#define TZPM_TZPCTL1_FLEXCOM4(x)                 (((x) << 20) & GENMASK(20, 20))
#define TZPM_TZPCTL1_FLEXCOM4_M                  GENMASK(20, 20)
#define TZPM_TZPCTL1_FLEXCOM4_X(x)               (((x) & GENMASK(20, 20)) >> 20)

#define TZPM_TZPCTL1_SHA(x)                      (((x) << 19) & GENMASK(19, 19))
#define TZPM_TZPCTL1_SHA_M                       GENMASK(19, 19)
#define TZPM_TZPCTL1_SHA_X(x)                    (((x) & GENMASK(19, 19)) >> 19)

#define TZPM_TZPCTL1_XDMA(x)                     (((x) << 18) & GENMASK(18, 18))
#define TZPM_TZPCTL1_XDMA_M                      GENMASK(18, 18)
#define TZPM_TZPCTL1_XDMA_X(x)                   (((x) & GENMASK(18, 18)) >> 18)

#define TZPM_TZPCTL1_FLEXCOM3(x)                 (((x) << 17) & GENMASK(17, 17))
#define TZPM_TZPCTL1_FLEXCOM3_M                  GENMASK(17, 17)
#define TZPM_TZPCTL1_FLEXCOM3_X(x)               (((x) & GENMASK(17, 17)) >> 17)

#define TZPM_TZPCTL1_FLEXCOM2(x)                 (((x) << 16) & GENMASK(16, 16))
#define TZPM_TZPCTL1_FLEXCOM2_M                  GENMASK(16, 16)
#define TZPM_TZPCTL1_FLEXCOM2_X(x)               (((x) & GENMASK(16, 16)) >> 16)

#define TZPM_TZPCTL1_QSPI1(x)                    (((x) << 5) & GENMASK(5, 5))
#define TZPM_TZPCTL1_QSPI1_M                     GENMASK(5, 5)
#define TZPM_TZPCTL1_QSPI1_X(x)                  (((x) & GENMASK(5, 5)) >> 5)

#define TZPM_TZPCTL1_AESB_ASC(x)                 (((x) << 4) & GENMASK(4, 4))
#define TZPM_TZPCTL1_AESB_ASC_M                  GENMASK(4, 4)
#define TZPM_TZPCTL1_AESB_ASC_X(x)               (((x) & GENMASK(4, 4)) >> 4)

#define TZPM_TZPCTL1_AES(x)                      (((x) << 3) & GENMASK(3, 3))
#define TZPM_TZPCTL1_AES_M                       GENMASK(3, 3)
#define TZPM_TZPCTL1_AES_X(x)                    (((x) & GENMASK(3, 3)) >> 3)

#define TZPM_TZPCTL1_TRNG(x)                     (((x) << 2) & GENMASK(2, 2))
#define TZPM_TZPCTL1_TRNG_M                      GENMASK(2, 2)
#define TZPM_TZPCTL1_TRNG_X(x)                   (((x) & GENMASK(2, 2)) >> 2)

#define TZPM_TZPCTL1_FLEXCOM1(x)                 (((x) << 1) & GENMASK(1, 1))
#define TZPM_TZPCTL1_FLEXCOM1_M                  GENMASK(1, 1)
#define TZPM_TZPCTL1_FLEXCOM1_X(x)               (((x) & GENMASK(1, 1)) >> 1)

#define TZPM_TZPCTL1_FLEXCOM0(x)                 ((x) & GENMASK(0, 0))
#define TZPM_TZPCTL1_FLEXCOM0_M                  GENMASK(0, 0)
#define TZPM_TZPCTL1_FLEXCOM0_X(x)               ((x) & GENMASK(0, 0))

/*      TZPM:TZPM_REGS:TZPCTL2 */
#define TZPM_TZPCTL2              0x10

#define TZPM_TZPCTL2_TZPM(x)                     (((x) << 1) & GENMASK(1, 1))
#define TZPM_TZPCTL2_TZPM_M                      GENMASK(1, 1)
#define TZPM_TZPCTL2_TZPM_X(x)                   (((x) & GENMASK(1, 1)) >> 1)

#define TZPM_TZPCTL2_PKCC(x)                     ((x) & GENMASK(0, 0))
#define TZPM_TZPCTL2_PKCC_M                      GENMASK(0, 0)
#define TZPM_TZPCTL2_PKCC_X(x)                   ((x) & GENMASK(0, 0))

/*      TZPM:TZPM_REGS:TZPCTL3 */
#define TZPM_TZPCTL3              0x14

#define TZPM_TZPCTL3_PCIE_IB(x)                  (((x) << 27) & GENMASK(27, 27))
#define TZPM_TZPCTL3_PCIE_IB_M                   GENMASK(27, 27)
#define TZPM_TZPCTL3_PCIE_IB_X(x)                (((x) & GENMASK(27, 27)) >> 27)

#define TZPM_TZPCTL3_RTE(x)                      (((x) << 26) & GENMASK(26, 26))
#define TZPM_TZPCTL3_RTE_M                       GENMASK(26, 26)
#define TZPM_TZPCTL3_RTE_X(x)                    (((x) & GENMASK(26, 26)) >> 26)

#define TZPM_TZPCTL3_FDMA(x)                     (((x) << 25) & GENMASK(25, 25))
#define TZPM_TZPCTL3_FDMA_M                      GENMASK(25, 25)
#define TZPM_TZPCTL3_FDMA_X(x)                   (((x) & GENMASK(25, 25)) >> 25)

#define TZPM_TZPCTL3_EXT_INITIATOR(x)            (((x) << 24) & GENMASK(24, 24))
#define TZPM_TZPCTL3_EXT_INITIATOR_M             GENMASK(24, 24)
#define TZPM_TZPCTL3_EXT_INITIATOR_X(x)          (((x) & GENMASK(24, 24)) >> 24)

#endif /* _LAN966X_REGS_H_ */
