/*
 * Copyright (C) 2022 Microchip Technology Inc. and its subsidiaries.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/* This file is autogenerated by cml-utils 2022-08-10 11:51:45 +0200.
 * Commit ID: 8250f2b4e2ac5ac9a8c0a9af8951476f4c704e87
 */

/* LAN969X targets */

#ifndef _LAN969X_TARGETS_SR_H_
#define _LAN969X_TARGETS_SR_H_

#define LAN969X_AES_BASE                 UL(0xE004C000)
#define LAN969X_AESB_ASC_BASE            UL(0xE0050000)
#define LAN969X_CPU_BASE                 UL(0xE00C0000)
#define LAN969X_CPU_SYSCNT_BASE          UL(0xE8000000)
#define LAN969X_CPU_SYSCNT_RO_BASE       UL(0xE8000000)
#define LAN969X_DDR_PHY_BASE             UL(0xE0084000)
#define LAN969X_DDR_UMCTL2_BASE          UL(0xE0080000)
#define LAN969X_DEVCPU_ORG0_BASE         UL(0xE2000000)
#define LAN969X_DEVCPU_ORG1_BASE         UL(0xE3000000)
#define LAN969X_DEVCPU_ORG2_BASE         UL(0xE3400000)
#define LAN969X_FDMA_BASE                UL(0xE00C0400)
#define LAN969X_FLEXCOM_0_BASE           UL(0xE0040000)
#define LAN969X_FLEXCOM_1_BASE           UL(0xE0044000)
#define LAN969X_FLEXCOM_2_BASE           UL(0xE0060000)
#define LAN969X_FLEXCOM_3_BASE           UL(0xE0064000)
#define LAN969X_GCB_BASE                 UL(0xE2010000)
#define LAN969X_GIC400_BASE              UL(0xE8C10000)
#define LAN969X_GPV_BASE                 UL(0xE8B00000)
#define LAN969X_HICM_BASE                UL(0xE0810000)
#define LAN969X_HMATRIX2_BASE            UL(0xE0800000)
#define LAN969X_MCAN_0_BASE              UL(0xE081C000)
#define LAN969X_MCAN_1_BASE              UL(0xE0820000)
#define LAN969X_MCAN_TIMER_BASE          UL(0xE0824000)
#define LAN969X_OTP_BASE                 UL(0xE0021000)
#define LAN969X_PCIE_CFG_BASE            UL(0xE00D0000)
#define LAN969X_PCIE_DBI_BASE            UL(0xE0400000)
#define LAN969X_PCIE_PHY_PCS_BASE        UL(0xE0088000)
#define LAN969X_PCIE_PHY_PMA_BASE        UL(0xE2100000)
#define LAN969X_PCIE_PHY_WRAP_BASE       UL(0xE20F0000)
#define LAN969X_PKE_BASE                 UL(0x00080000)
#define LAN969X_PTP_BASE                 UL(0xE2040000)
#define LAN969X_QS_BASE                  UL(0xE2030000)
#define LAN969X_QSPI_0_BASE              UL(0xE0804000)
#define LAN969X_QSPI_2_BASE              UL(0xE0834000)
#define LAN969X_SDMMC_0_BASE             UL(0xE0830000)
#define LAN969X_SDMMC_1_BASE             UL(0xE0838000)
#define LAN969X_SHA_BASE                 UL(0xE006C000)
#define LAN969X_SJTAG_BASE               UL(0xE0020000)
#define LAN969X_TIMERS_BASE              UL(0xE008C000)
#define LAN969X_TRNG_BASE                UL(0xE0048000)
#define LAN969X_TZAESBNS_BASE            UL(0xE0814000)
#define LAN969X_TZAESBS_BASE             UL(0xE0818000)
#define LAN969X_TZC_CSS_BASE             UL(0xE0099000)
#define LAN969X_TZC_MAIN_HSS_BASE        UL(0xE0098000)
#define LAN969X_TZPM_BASE                UL(0xE0000000)
#define LAN969X_USB3_BASE                UL(0x00300000)
#define LAN969X_UVOV_BASE                UL(0xE0094000)
#define LAN969X_WDT_BASE                 UL(0xE0090000)
#define LAN969X_XDMAC_BASE               UL(0xE0068000)

#endif /* _LAN969X_TARGETS_SR_H_ */
