/*
 * Copyright (C) 2022 Microchip Technology Inc. and its subsidiaries.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/* This file is autogenerated by cml-utils 2022-04-29 10:59:14 +0200.
 * Commit ID: 017d325c9b7b3982ae6c2921d96e68e61ed078e2
 */

/* LAN966X targets */

#ifndef _LAN966X_TARGETS_A0_H_
#define _LAN966X_TARGETS_A0_H_

#define LAN966X_AES_BASE                 UL(0xE004C000)
#define LAN966X_AESB_ASC_BASE            UL(0xE0050000)
#define LAN966X_AFI_BASE                 UL(0xE2120000)
#define LAN966X_ANA_BASE                 UL(0xE2140000)
#define LAN966X_CA7_DBG_BASE             UL(0xE8800000)
#define LAN966X_CHIP_TOP_BASE            UL(0xE2010000)
#define LAN966X_CPU_BASE                 UL(0xE00C0000)
#define LAN966X_CPU_SYSCNT_BASE          UL(0xE8843000)
#define LAN966X_CPU_SYSCNT_RO_BASE       UL(0xE8900000)
#define LAN966X_CUPHY_1_BASE             UL(0xE00A0600)
#define LAN966X_CUPHY_2_BASE             UL(0xE00A0A00)
#define LAN966X_DDR_PHY_BASE             UL(0xE0084000)
#define LAN966X_DDR_UMCTL2_BASE          UL(0xE0080000)
#define LAN966X_DEV_0_BASE               UL(0xE2034000)
#define LAN966X_DEV_1_BASE               UL(0xE2038000)
#define LAN966X_DEV_2_BASE               UL(0xE203C000)
#define LAN966X_DEV_3_BASE               UL(0xE2040000)
#define LAN966X_DEV_4_BASE               UL(0xE2044000)
#define LAN966X_DEV_5_BASE               UL(0xE2048000)
#define LAN966X_DEV_6_BASE               UL(0xE204C000)
#define LAN966X_DEV_7_BASE               UL(0xE2050000)
#define LAN966X_FDMA_BASE                UL(0xE00C0400)
#define LAN966X_FLEXCOM_0_BASE           UL(0xE0040000)
#define LAN966X_FLEXCOM_1_BASE           UL(0xE0044000)
#define LAN966X_FLEXCOM_2_BASE           UL(0xE0060000)
#define LAN966X_FLEXCOM_3_BASE           UL(0xE0064000)
#define LAN966X_FLEXCOM_4_BASE           UL(0xE0070000)
#define LAN966X_GCB_BASE                 UL(0xE2004000)
#define LAN966X_GIC400_BASE              UL(0xE8C10000)
#define LAN966X_GPV_BASE                 UL(0xE8B00000)
#define LAN966X_HICM_BASE                UL(0xE0810000)
#define LAN966X_HMATRIX2_BASE            UL(0xE0800000)
#define LAN966X_HSIO_BASE                UL(0xE202C000)
#define LAN966X_MCAN_0_BASE              UL(0xE081C000)
#define LAN966X_MCAN_1_BASE              UL(0xE0820000)
#define LAN966X_MEP_BASE                 UL(0xE201C000)
#define LAN966X_ORG_0_BASE               UL(0xE2000000)
#define LAN966X_ORG_1_BASE               UL(0xE2400000)
#define LAN966X_OTP_BASE                 UL(0xE0021000)
#define LAN966X_PCIE_CFG_BASE            UL(0xE00D0000)
#define LAN966X_PCIE_DBI_BASE            UL(0xE0400000)
#define LAN966X_PTP_BASE                 UL(0xE200C000)
#define LAN966X_QS_BASE                  UL(0xE2008000)
#define LAN966X_QSPI_0_BASE              UL(0xE0804000)
#define LAN966X_QSPI_1_BASE              UL(0xE0054000)
#define LAN966X_QSPI_2_BASE              UL(0xE0834000)
#define LAN966X_QSYS_BASE                UL(0xE2100000)
#define LAN966X_REW_BASE                 UL(0xE2014000)
#define LAN966X_RTE_BASE                 UL(0xE2600000)
#define LAN966X_SDMMC_BASE               UL(0xE0830000)
#define LAN966X_SHA_BASE                 UL(0xE006C000)
#define LAN966X_SJTAG_BASE               UL(0xE0020000)
#define LAN966X_SYS_BASE                 UL(0xE2028000)
#define LAN966X_TIMER1_BASE              UL(0xE0824000)
#define LAN966X_TIMERS_BASE              UL(0xE008C000)
#define LAN966X_TRNG_BASE                UL(0xE0048000)
#define LAN966X_TZAESBNS_BASE            UL(0xE0814000)
#define LAN966X_TZAESBS_BASE             UL(0xE0818000)
#define LAN966X_TZPM_BASE                UL(0xE0004000)
#define LAN966X_UDPHS0_BASE              UL(0xE0808000)
#define LAN966X_UVOV_BASE                UL(0xE0094000)
#define LAN966X_VCAP_0_BASE              UL(0xE2018000)
#define LAN966X_VCAP_1_BASE              UL(0xE2020000)
#define LAN966X_VCAP_2_BASE              UL(0xE2024000)
#define LAN966X_WDT_BASE                 UL(0xE0090000)
#define LAN966X_XDMAC_BASE               UL(0xE0068000)

#endif /* _LAN966X_TARGETS_A0_H_ */
