name: ARM Trusted Firmware for LAN969x

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/statropy/docker-bsp-buildenv:latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fix ownership
        run: chown -R ubuntu:ubuntu $GITHUB_WORKSPACE

      - name: Build TF-A
        run: |
            su ubuntu
            ./scripts/lan969x_build.rb

# TODO Create artifacts
