name: ARM Trusted Firmware for LAN969x

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
        image: ghcr.io/statropy/docker-bsp-buildenv:latest
        options: --user ubunutu

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fix ownership
        run: chown -R ubuntu:ubuntu $GITHUB_WORKSPACE

      - name: Build TF-A
        run: ./scripts/lan969x_build.rb
